### ISSUE TITLE
Error page system

### ISSUE THREAD

**Issue by balack** [magepal/magento2-gmailsmtpapp#1]
After setup module and enable, my system config error white page http://pasteboard.co/K9SQyEA.png

**Comment by srenon** [comment]
Can you check your php error log? Did you try log out and back in?

**Comment by balack** [comment]
This is my log
[2016-01-12 18:07:26] main.CRITICAL: Class MagePal\GmailSmtpApp\Model\Config\Source\Authtype does not exist [] []
[2016-01-12 19:10:19] main.CRITICAL: Class MagePal\GmailSmtpApp\Model\Config\Source\Authtype does not exist [] []
[2016-01-12 19:10:40] main.CRITICAL: Class MagePal\GmailSmtpApp\Model\Config\Source\Authtype does not exist [] []

**Comment by balack** [comment]
This is my log (i use magento 2.0)
[2016-01-12 18:07:26] main.CRITICAL: Class MagePal\GmailSmtpApp\Model\Config\Source\Authtype does not exist [] []
[2016-01-12 19:10:19] main.CRITICAL: Class MagePal\GmailSmtpApp\Model\Config\Source\Authtype does not exist [] []
[2016-01-12 19:10:40] main.CRITICAL: Class MagePal\GmailSmtpApp\Model\Config\Source\Authtype does not exist [] []

**Comment by srenon** [comment]
Can you log into your server and check if that file exist at the given path?

See https://github.com/magepal/magento2-gmailsmtpapp/blob/master/Model/Config/Source/Authtype.php

**Comment by balack** [comment]
I'm setup ok! http://easycaptures.com/3243698637 
And is testing

Thank you so much

**Comment by binhton** [comment]
Where is the log file to see if the mails sent correctly?  We currently don't see any email sent out.  We use regular Gmail account, not Google Apps.  Do I have to open any incoming port on server?

**Comment by srenon** [comment]
@balack is it working now?

**Comment by balack** [comment]
I'm config with my gmail account but it is not work, don't send mail, don't log :(

**Comment by srenon** [comment]
ssh into your server and run 

`php -r "mail('s@gmail.com', 'My Subject', 'test');"`

What is the result?

**Comment by balack** [comment]
I have run php -r "mail('balackhuynh@gmail.com', 'My Subject', 'test');" 

Result, I get 1 email to balackhuynh@gmail.com

http://easycaptures.com/8882986633

**Comment by srenon** [comment]
Please download the latest version and let me know what error message you are getting

![image](https://cloud.githubusercontent.com/assets/1415141/12380589/5383a450-bd44-11e5-9f20-62f32e5ab9eb.png)

**Comment by balack** [comment]
This is my config: http://pasteboard.co/SMtivwM.png

And result: http://pasteboard.co/SMySiSl.png

Thank you :)

**Comment by srenon** [comment]
Try https://support.google.com/accounts/answer/6010255?hl=en

**Comment by binhton** [comment]
@srenon, Thanks for pointing out those support sites.  I am currently working with balack to get it working.  After changing the security in Gmail account for "less secure app" and "disable the capcha", we can send and receive the test email now.  However, we don't see the actual email sent to customer after the order.  I also went to Admin -> Sales -> Orders -> Order and use Send Email to resend the order email, and still didn't see the email.  No error when I used the Send Email option.  Any idea?
Thanks

**Comment by srenon** [comment]
Sorry please download the new version

**Comment by srenon** [comment]
@balack @binhton ... Are you still having this issue?

**Comment by balack** [comment]
thank you so much
It isn't send mail when has order, create user.
I'm use 1 other ex.

**Comment by srenon** [comment]
Are you running the latest version? Is it sending or not send order email?

**Comment by balack** [comment]
Yes, i'm running latest version (follow #issuecomment-172726330)

**Comment by srenon** [comment]
Does the contact form work? Did you clear cache?

**Comment by balack** [comment]
Yes, im test contact form and run php -f bin/magento cache:flush from cmd ssh, clear cache browser but it isn't work :(
