### ISSUE TITLE
Full SMTP

### ISSUE THREAD

**Issue by mozgbrasil** [magepal/magento2-gmailsmtpapp#11]
Hello .. Good evening

I just installed your module and see that only has the possibility of using Gmail, I use Zoho, it would be possible I use another type of SMTP service?

**Comment by srenon** [comment]
I will be creating a new module shortly with greater support for more smtp providers.

But looking at Zoho smtp setting it should be the same as gmail

Try using the TLS setting and change the host to smtp.zoho.com
