### ISSUE TITLE
Connection timed out in Transport.php:78

### ISSUE THREAD

**Issue by kayintveen** [magepal/magento2-gmailsmtpapp#12]
Hi, great tool. 
But i get a Timeout. 

```
Next Magento\Framework\Exception\MailException: Connection timed out in /home/forge/domain.com/vendor/magepal/magento2-gmailsmtpapp/Model/Transport.php:78
Stack trace:
#0 /home/forge/domain.com/app/code/Magento/Customer/Model/EmailNotification.php(239): MagePal\GmailSmtpApp\Model\Transport->sendMessage()
#1 /home/forge/domain.com/app/code/Magento/Customer/Model/EmailNotification.php(320): Magento\Customer\Model\EmailNotification->sendEmailTemplate(Object(Magento\Customer\Model\Data\Customer), 'customer/passwo...', 'customer/passwo...', Array, '1')
#2 /home/forge/domain.com/app/code/Magento/Customer/Model/AccountManagement.php(507): Magento\Customer\Model\EmailNotification->passwordResetConfirmation(Object(Magento\Customer\Model\Data\Customer))
#3 [internal function]: Magento\Customer\Model\AccountManagement->initiatePasswordReset('k.veen@microdes...', 'email_reset', '1')
#4 /home/forge/domain.com/lib/internal/Magento/Framework/Interception/Interceptor.php(146): call_user_func_array(Array, Array)
#5 /home/forge/domain.com/var/generation/Magento/Customer/Model/AccountManagement/Interceptor.php(91): Magento\Customer\Model\AccountManagement\Interceptor->___callPlugins('initiatePasswor...', Array, Array)
#6 /home/forge/domain.com/app/code/Magento/Customer/Controller/Account/ForgotPasswordPost.php(72): Magento\Customer\Model\AccountManagement\Interceptor->initiatePasswordReset('k.veen@microdes...', 'email_reset')
#7 /home/forge/domain.com/var/generation/Magento/Customer/Controller/Account/ForgotPasswordPost/Interceptor.php(25): Magento\Customer\Controller\Account\ForgotPasswordPost->execute()
#8 /home/forge/domain.com/lib/internal/Magento/Framework/App/Action/Action.php(102): Magento\Customer\Controller\Account\ForgotPasswordPost\Interceptor->execute()
#9 [internal function]: Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))

```

**Comment by srenon** [comment]
What smtp server are you using? 

Also does it work for other email related task (ie customer contact or resent order confirmation)?

**Comment by kayintveen** [comment]
The default one already configured. smtp.gmail.com
username = my google apps email
password = my google apps password.

**Comment by srenon** [comment]
1. "Connection timed out" normally mean that you can not connect to the server, so does the test connection work in the admin?

2. What version of magento are you running?

3. Does it work for other email related task (ie customer contact or resent order confirmation)?

**Comment by kayintveen** [comment]
Its a develop location. emails where not working at all (i think the basic forge server has no php mail setup correctly) this is why i installed your extension

its Magento 2.0.0.

**Comment by srenon** [comment]
1. What OS (windows, linux, os x) are you running?

2. What version of magento 2.0 are you running (2.0.0, 2.0.1,  2.0.2,  2.0.3,  2.0.4,  2.0.5)?

**Comment by srenon** [comment]
From your server try

```php -r "mail('s@gmail.com', 'My Subject', 'test');"```

**Comment by kayintveen** [comment]
1. Ubuntu 4.8.2-19ubuntu1 (via laravel Forge for ease and quick setup, on php7) 
2. Magento 2.0.0.

your ssh command returned. 
sh: 1: /usr/sbin/sendmail: not found

**Comment by srenon** [comment]
They maybe a bug in magento v2.0.0 on php7 which affect password encryption see https://github.com/magepal/magento2-gmailsmtpapp/issues/7

You also need to get php mail working see http://askubuntu.com/questions/47609/how-to-have-my-php-send-mail

**Comment by srenon** [comment]
You issue should be cause by either (1) mail not installe, (2) bug in magento or (3) both.

**Comment by kayintveen** [comment]
im testing later tonight with installing and upgrading magento. thanks so far.

**Comment by srenon** [comment]
Let me know if you still having issue

**Comment by qubaish-techverx** [comment]
I am having the same issue would you please help me where i did mistake. 

First I used default serve "smtp.gmail.com" with my username and password and it works good to me.

Now i am using this server "jpcooke.com.outbound10.mxlogic.net" but it gives time out issue.

**Comment by srenon** [comment]
@qubaish-techverx 
Does "jpcooke.com.outbound10.mxlogic.net" point to a google/gmail email server?

**Comment by qubaish-techverx** [comment]
@srenon no it is not pointing to google/gmail server . What we have other solution to handle this issue any idea ?

**Comment by srenon** [comment]
@qubaish-techverx ...

Is this your own smtp server?  

Timeout normally mean that it can not connect, are the correct port open on the sever?

Can you login using a thirdparty app (ie iPhone, outlook etc)?

**Comment by qubaish-techverx** [comment]
@srenon 

No its client server

And yeah using third party app it works.

**Comment by srenon** [comment]
@qubaish-techverx ....

Since this is a third party mail server it hard for me to debug... What I would recommend is to take a look at this https://github.com/magepal/magento2-gmailsmtpapp/blob/master/Controller/Adminhtml/Test/Index.php#L69 and try the different combination to see which work (port etc).

Than take a look at https://framework.zend.com/manual/1.12/en/zend.mail.smtp-authentication.html and http://stackoverflow.com/questions/17785749/zend-email-using-gmail-smtp
