### ISSUE TITLE
Amazon SES

### ISSUE THREAD

**Issue by milanstojanov** [magepal/magento2-gmailsmtpapp#13]
Hello, 

Can you provide some guidelines on how can I make this work with Amazon SES? 

Thanks, 
Mian

**Comment by srenon** [comment]
Log into magento 2 admin then go to Stores -> Configuration -> Advanced -> System -> Gmail/Google Apps SMTP Pro.

> Well you fill all the fields exactly like you would if you were using Gmail. The catch here is that Amazon SES username is not an email. So if you want to use the test button, you will need to provide a sender email so it can process it.

See https://github.com/magepal/magento2-gmailsmtpapp/pull/5

**Comment by milanstojanov** [comment]
Thanks! However this still doesn't work. 


![screen shot 2016-06-03 at 1 54 48 pm](https://cloud.githubusercontent.com/assets/2226059/15777764/2c2d56de-2992-11e6-8755-398e61ee9273.png)

This is how I configured it in the backend, and I am always getting "Authentication Credentials Invalid" response when I test from the backend. I am 100% sure that my credentials are correct, since I am using them on other Magento1 projects. 

Wondering if you have a quick tip on what may be wrong here before I start digging into the extension?

Thanks very much!

**Comment by srenon** [comment]
What version of magento 2.0.x and Php are you running ?

Try re entering the password (DO NOT SAVE), the press test

Base on the error msg, you are actually connection to aws but the info not current (the was a bug in earlier version of magento when using php 7)

Authentication Credentials Invalid
535 Authentication Credentials Invalid
Your email-sending application did not provide the correct SMTP credentials to Amazon SES. Note that your SMTP credentials are not the same as your AWS credentials. For more information, see Obtaining Your Amazon SES SMTP Credentials.

**Comment by srenon** [comment]
I going to close this issue since you have not reply in a while.
