### ISSUE TITLE
Could Not Open Socket

### ISSUE THREAD

**Issue by arvind07** [magepal/magento2-gmailsmtpapp#15]
I tried to configure my gmail account for sending emails on my Windows machine. But when sending test email, it gives following error: http://joxi.ru/V2VBaKvh0oXK62

Here are my configurations: http://joxi.ru/Dr86vE9uk8LM62

I have enable Access for less secure apps in my gmail account: http://joxi.ru/E2pdVgnfBNpGN2

My PHP streams: http://joxi.ru/krDO8Dkt0jy4QA

Is this something related to my gmail account?

Thanks

**Comment by srenon** [comment]
@arvind07  I think is more of a server php ssl config issue and not a gmail issue.

It seem as if you already review http://stackoverflow.com/questions/28433816/how-to-fix-could-not-open-socket-in-zend-mail-zend-framework-2 but i still think the issue is php ssl. 

What version of php are you running?

**Comment by arvind07** [comment]
I am using Php 5.6.15 on xampp Windows 8

Best Regards,
Arvind

**Comment by shahankitb997** [comment]
I'm facing same issue on my WAMP Version 3.0.4

**Comment by arvind07** [comment]
It will not work on WAMP/XAMPP. I had same issue. But it works on the server with correct SSL certificate.

**Comment by srenon** [comment]
@arvind07 @shahankitb997 .. Can you do a quick test?

Open app/code/MagePal/GmailSmtpApp/Controller/Adminhtml/Test/Index.php

change from 
```
$smtpConf = array(
            'auth' => strtolower($request->getPost('auth')),
            'ssl' => $request->getPost('ssl'),
            'username' => $username,
            'password' => $password
        );
```

to 

```
$smtpConf = array(
            'auth' => strtolower($request->getPost('auth')),
            'ssl' => $request->getPost('ssl'),
            'username' => $username,
            'password' => $password,
           'port'=> 587  // or 465
        );
```

Then try doing a "test config" in module config

Take a look at http://stackoverflow.com/a/21957952/1191288  and let me know which setting work

**Comment by srenon** [comment]
@shahankitb997 ... try downloading the new version and try again

**Comment by shahankitb997** [comment]
Thanks @arvind07 for suggestion.  @srenon Thanks for your response & update code accordingly. Many Thanks.

I have installed new version on my WAMP Windows 10.
On Admin Configuration for Gmail i have both ports, when i try to send Test Email. 

It gives 

`Warning: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed in D:\wamp\www\magento2\vendor\magento\zendframework1\library\Zend\Mail\Protocol\Smtp.php on line 206`

@arvind07  Please check on Server with SSL Server. It it works fine then you can close issue

**Comment by srenon** [comment]
@shahankitb997 .... for future reference could you provide screen shot of the setting to make it work



![image](https://cloud.githubusercontent.com/assets/1415141/18348956/7989a986-759c-11e6-97b2-72350e1232fc.png)


See https://support.google.com/a/answer/176600?hl=en

**Comment by akamura** [comment]
@srenon I receive connection timed out when testing.
I have configured a sparkpost account that is equal to SES or Mailgun or Mandrill.

Find my screenshots below

![screen shot 2016-09-09 at 17 44 41](https://cloud.githubusercontent.com/assets/20488700/18393461/ba8ab636-76b5-11e6-9448-5c6b31ebeb99.png)
![screen shot 2016-09-09 at 17 44 53](https://cloud.githubusercontent.com/assets/20488700/18393460/ba829096-76b5-11e6-9da7-011990f86f98.png)

**Comment by srenon** [comment]
Is your magento code run on there network or on a different computer (i.e local dev)?

"timeout" normally mean that i can not connect, which could be :

-  Your API key must have the 'Send via SMTP' permission enabled

- You should have one or more verified sending domains configured in your SparkPost account (for example, 'myawesomedomain.com')

- You sending domain should be listed as 'ready to send' in the Sending Domains dashboard.

- If you are using local client software to send messages to SparkPost, make sure that your firewall is set to allow sending on port 587

Did you review https://support.sparkpost.com/customer/portal/articles/1988470-smtp-connection-problems

**Comment by akamura** [comment]
@srenon thank you for your suggestion.

My website is currently on a local development VPS on Vmware under a .dev domain since the website is still not public.
On Magento 1.x platform I had no problem testing mail sending with sparkpost, of course Magento 2 platform is completely different but I don't think the problem is the server.

I confirm my domain is ready to send email and have SPF and DKIM configured, plus I have the send via SMTP option enabled on the API keys.

I have even disabled the firewall on the development server to test if that was the problem but the connection is still time out.

Thanks

**Comment by srenon** [comment]
@akamura ... you need to change "Authentication method" to "LOGIN" 

![image](https://cloud.githubusercontent.com/assets/1415141/18395511/a68cb9be-768c-11e6-9631-bb7827f2df72.png)


"You need to use AUTH LOGIN as the authentication approach"

See  https://support.sparkpost.com/customer/portal/articles/1988470-smtp-connection-problems

**Comment by akamura** [comment]
@srenon yes I have that but still not work.

![screen shot 2016-09-09 at 19 04 26](https://cloud.githubusercontent.com/assets/20488700/18395760/5be0159e-76c0-11e6-9b20-0a4d587845c7.png)

**Comment by srenon** [comment]
As you can see from the above screenshot my test did not return a connect timeout but an actual valid response from there server.

In your "test setting" did you include a valid email that authorize on there server? 

Did try to use port 2525?

**Comment by akamura** [comment]
Ok I finally discovered where was the issue, I made a mistake leaving port 465 set in your source code "app/code/MagePal/GmailSmtpApp/Controller/Adminhtml/Test/Index.php" now I set back the line to  'port' => $request->getPost('smtpport') and the timeout error is gone.

But now when I test a new error appear:

![screen shot 2016-09-09 at 19 48 31](https://cloud.githubusercontent.com/assets/20488700/18397044/c2721d06-76c6-11e6-8fc9-7d8ab3719989.png)

**Comment by srenon** [comment]
Take a look at https://community.spiceworks.com/topic/146956-smtp-500-5-5-2-unrecognized-command

**Comment by akamura** [comment]
Strange thing, the test mail doesn't work, but overall Magento is now sending mail correctly.

**Comment by akamura** [comment]
hi @srenon did your module disable default Magento SMTP? I'm asking because I decided to install postfix locally on the server and after disabling your module now Magento isn't sending any email at all, even if I enable again the module.

Look for more informations on the issue I have opened here
https://github.com/magento/magento2/issues/6648

Thanks
Matia

**Comment by srenon** [comment]
The module rewrite `<preference for="\Magento\Framework\Mail\Transport" type="MagePal\GmailSmtpApp\Model\Transport"/>` see https://github.com/magepal/magento2-gmailsmtpapp/blob/master/etc/di.xml 

But if you disable it then it should not.... try debugging by putting `die('core')/die('GmailSmtpApp')` in the construct and see which message get display

**Comment by akamura** [comment]
Thanks for your suggestion it help me immediately realize where the problem was. I left a note on the original post.

**Comment by srenon** [comment]
@akamura .... Ok... let me know if you have anymore issues
