### ISSUE TITLE
Email not being sent while test emails working perfectly

### ISSUE THREAD

**Issue by liquidia** [magepal/magento2-gmailsmtpapp#16]
This extension is  not triggering any email on order (did not tested for other transnational emails) while test emails are working fine. 

Other Details:
Magento version: 2.1
Server detail: Nginx, firewall (fail2ban / iptables)

Thanks

**Comment by srenon** [comment]
What version of php are you running?

**Comment by liquidia** [comment]
sorry i forgot to mention its php7

**Comment by srenon** [comment]
What exact version of 7? 

After saving the password if you do a test does it still work?

See issue https://github.com/magepal/magento2-gmailsmtpapp/issues/7

**Comment by liquidia** [comment]
Yes test email working fine even after saving as for php version its 7.0.8 here is more detail:

Zend Engine v3.0.0,with Zend OPcache v7.0.8-3+deb.sury.org~trusty+1

**Comment by srenon** [comment]
Can you try on the 'contact us' page to see if email been send.

Does order email work when this module is disabled? Is your cron setup correctly?

**Comment by liquidia** [comment]
Yes contact form working fine ( sending message to admin / owner of store but no notification to visitor who fills form i guess thats how it works) 

Yes email works without this plugin earlier it wasn't but after configuring corn with following code:
`*/1 * * * * www-data php /var/www/html/magento2/bin/magento cron:run
*/1 * * * * www-data php /var/www/html/magento2/update/cron.php
*/1 * * * * www-data php /var/www/html/magento2/bin/magento setup:cron:run`

Its working fine.  i have "postfix" installed on system.

**Comment by liquidia** [comment]
just noticed following error when trying to send shipping notification:

"Error 5.1.2: The address specified is not a valid RFC-5321"

**Comment by liquidia** [comment]
shipping confrimation email working perfectly after removing coma separated emails ..bcc

**Comment by srenon** [comment]
Ok.... I'll look into do this a different way to support multiple bcc. 

I see this issue many times (even in default magento ), so I always recommend using distribution list for example 'sales/orders@xyz.com'

**Comment by liquidia** [comment]
all email notifications are working fine now after removing blank space before email address from following field Send Order Comment Email Copy To"	in configuration  > sales > sales email..

I wulod like to donate. let me know how can i do it (paypal?) thanks for the help

**Comment by srenon** [comment]
You more than welcome to donate https://www.paypal.me/srenon

Thanks,

**Comment by liquidia** [comment]
hi cant pay through this link (not working in my country) can you send me $50 paypal invoice at liquidiagraphics@gmail.com

P.S:Will remove this message as soon as you send me invoice

Thanks

**Comment by liquidia** [comment]
Thanks Done!

**Comment by ajayshukla** [comment]
Hello,

I am also having the same issue with following details:

Provider: AWS SES
Magento : 2.2.4
Server: AWS
PHP: 7.1.17

I am able to send test mail but order emails are not working. 

Can you please suggest what I am missing?

Thanks

**Comment by srenon** [comment]
@ajayshukla .... please take a look at the newer issue ie https://github.com/magepal/magento2-gmail-smtp-app/issues/113
