### ISSUE TITLE
Not able to send mails. M2.1.0 + AWS SES

### ISSUE THREAD

**Issue by apurv-anand** [magepal/magento2-gmailsmtpapp#17]
I am trying to send transaction mails from Magento 2.1.0 + AWS SES configured through this extension.

Errors:
[2016-08-04 12:20:39] main.CRITICAL: Zend_Mail_Protocol_Exception: Message rejected: Email address is not verified. The following identities failed the check in region US-EAST-1: abc@xyz.in

Next Magento\Framework\Exception\MailException: Message rejected: Email address is not verified. The following identities failed the check in region US-EAST-1: abc@xyz.in
 in /opt/bitnami/apps/magento/htdocs/app/code/MagePal/GmailSmtpApp/Model/Transport.php:78

My configurations are:
Auth method: Login
SSL: TLS (I tried SSL too)
Server details and credentials.
Set reply to and set return path: Yes.

Point to note that abc@xyz.in is a recipient address and there is no need to verify that. Sender address which is support@xyz.com is verified.

Help me crack this.

**Comment by srenon** [comment]
Take a look at http://docs.aws.amazon.com/ses/latest/DeveloperGuide/ses-errors.html

> Email address is not verified. The following identities failed the check in region <region>: <identity1>, <identity2>, <identity3>— You are trying to send email from an email address or domain that you have not verified with Amazon SES. This error could apply to the "From", "Source", "Sender", or "Return-Path" address. If your account is still in the sandbox, you also must verify every recipient email address except for the recipients provided by the Amazon SES mailbox simulator. If Amazon SES is not able to show all of the failed identities, the error message ends with an ellipsis.


Try changing the "Set reply to and set return path" to "no" to see what happen

**Comment by srenon** [comment]
All take a look at http://docs.aws.amazon.com/ses/latest/DeveloperGuide/limits.html

> Both in and out of the sandbox, you are required to verify the "From", "Source", "Sender", and "Return-Path" email addresses or domains, although not "Reply-To".

The "Return-Path" seem to be the issue, so please let me know if any change need to be make on my part

**Comment by apurv-anand** [comment]
Thanks srenon for a quick reply. 

The issue was sandbox + region selection. I have non-sandbox with a region, while others regions are on sandbox. AWS UI was not very loud to tell that I was on a wrong region. 

I moved to the right region that took me out of sandbox.

Thanks for helping out.
