### ISSUE TITLE
Warning and mail not send

### ISSUE THREAD

**Issue by mdcom77** [magepal/magento2-gmailsmtpapp#18]
Hello,

Trying to use the module with my SMTP (TLS) and receiving following message:

> Result
> 
> Warning: stream_socket_enable_crypto(): Peer certificate CN=`*.icnhost.net' did not match expected CN=`mail.myshop.eu' in /usr/share/nginx/html/magento2/vendor/magento/zendframework1/library/Zend/Mail/Protocol/Smtp.php on line 206

Magneto is running on different machine (subdominant A record) and mail is on hosting provider service.

**Comment by srenon** [comment]
Is your mail server running a valid ssl cert?

Take a look at http://stackoverflow.com/questions/30371910/phpmailer-generates-php-warning-stream-socket-enable-crypto-peer-certificate

**Comment by mdcom77** [comment]
Yes, certificate is valid, thank you for the link and for the module, succeed to fix the problem.

Best

**Comment by srenon** [comment]
@mdcom77 ... What was the problem?

**Comment by mdcom77** [comment]
The problem is pretty trivial - I am using valid certificate for the domain (it is actually subdomain) where my magento installation is. The actual domain is on shared hosting. When you use TLS with your mails on shared hosting and you haven't your own certificate - you are using the certificate of the shared hosting server. So I changed the name of mail server to match the name of the server from hosting provider and that was all.

**Comment by cayaners** [comment]
I had the same issue , when I use any STMP with magento2-gmailsmtpapp and it's keep give me this ERROR "Warning: stream_socket_enable_crypto(): Peer certificate CN=..........................." 
and after days of  hard search and  talking to support I found out that it wasn't a certificate  problem 
it was a security Setting on the WHM of my VPS hosting  that was restrict using remote STMP 
so I went to WHM as root then go Home »Security Center »SMTP Restrictions  and clicked on Disable 
after that everything work fine and I can send from STMP with no errors .
I hope this will help anyone has the same issue  .
