### ISSUE TITLE
Warning: include_once(Zend/Mail/Protocol/Smtp/Auth/LOGIN.php)

### ISSUE THREAD

**Issue by mswaidan** [magepal/magento2-gmailsmtpapp#2]
Thanks for this module. Install looks fine, I'm able to enter my credentials in Store/Config/Advanced/System, but when I try to send an email I'm getting this error:

main.ERROR: Warning: include_once(Zend/Mail/Protocol/Smtp/Auth/LOGIN.php): failed to open stream: No such file or directory in /var/www/magento2/vendor/magento/zendframework1/library/Zend/Loader.php on line 134

**Comment by srenon** [comment]
How did you install magento? Did you download it from magento.com or from github, so I can try to replicate these issue

**Comment by mswaidan** [comment]
I downloaded from magento.com , CE

I'm also not sure I installed your module correctly - I'd never used composer before so I just made a directory /var/www/magento2/app/code/MagePal/GmailSmtpApp and git cloned your module into it. Then added   'MagePal_GmailSmtpApp' => 1, to the modules array in /var/www/magento2/app/etc/config.php

**Comment by srenon** [comment]
This is how you should install your module after create the directory 

`./bin/magento module:enable MagePal_GmailSmtpApp`
`./bin/magento setup:upgrade`

**Comment by mswaidan** [comment]
Thanks, just did that.  Nothing appears to have changed - I forgot to mention in previous response that I ran setup:upgrade after adding MagePal_GmailSmtpApp to config.php

Still shows up in admin (same as before), still throws same error when trying to send an email.

**Comment by srenon** [comment]
I will download a copy tomorrow and test

**Comment by mswaidan** [comment]
Much appreciated!

**Comment by Krapulat** [comment]
Hello,

I have the same error when the system tries to send an e-mail:

Warning: File not found: Zend/Mail/Protocol/Smtp/Auth/LOGIN.php in /var/www/magento2/vendor/magento/zendframework1/library/Zend/Loader.php on line 134

Thanks.

**Comment by srenon** [comment]
@mswaidan @Krapulat ... What OS are you using?

**Comment by mswaidan** [comment]
Ubuntu 14.04

**Comment by srenon** [comment]
@mswaidan @Krapulat ... Please re-download and try again ... 

@Krapulat ... Remember to rename  LOGIN.php to Login.php

**Comment by Krapulat** [comment]
@srenon It works fine now.

Thanks!

**Comment by srenon** [comment]
@mswaidan @Krapulat ... Thanks for reporting this issue and testing.

**Comment by mswaidan** [comment]
@srenon Big thank you! Just an FYI - I had to check 'enable access for less secure apps' to get sending to work.

**Comment by srenon** [comment]
I will check my mail setting but are you using 'SSL' or 'TLS' in your system config?

Google didn't specify what "less secure apps" are https://support.google.com/accounts/answer/6010255?hl=en

**Comment by mswaidan** [comment]
Initially, it was set to TLS. I got an error, switched to SSL, got the same error. Dug around and found the 'less secure apps' recommendation, which cleared things up.

Ha, of course they didn't specify. Thanks again for this great module.

**Comment by srenon** [comment]
@mswaidan ... Thanks for your great debugging work (I'm was testing using an older gmail account that had the setting enabled already without realizing it)... I'm adding a new feature where you can test and see the error message in system config.
