### ISSUE TITLE
backend test mail & contact form not working

### ISSUE THREAD

**Issue by thagxt** [magepal/magento2-gmailsmtpapp#24]
I'm running Magento on a development server (not local machine) 
I point the domain, via hosts file, to dev server IP.

I've installed and set up the module, as explained. But In the backend when I try to send a "test mail" it says: `connection time out`.

on contact us page it gives me this:
`We can't process your request right now. Sorry, that's all we know.`

Magento 2.1.0
PHP Version 5.6.15

**Comment by srenon** [comment]
What smtp service are you using, google?

sendmail may not be installed try

```
php -r "mail('s@gmail.com', 'My Subject', 'test');"
```

Is the output 

```
sh: 1: /usr/sbin/sendmail: not found
```

**Comment by thagxt** [comment]
output is empty. 
it sends the email (I've put my email) and received it

**Comment by srenon** [comment]
what port are you using?

**Comment by thagxt** [comment]
btw yes, it's google.

SMTP Port 465

**Comment by srenon** [comment]
Try testing to see if the port is block

```
telnet smtp.gmail.com 465
```

Expected  result

```
Trying 173.194.204.109...
Connected to gmail-smtp-msa.l.google.com.
```

**Comment by thagxt** [comment]
```
Trying 173.194.192.109...
telnet: connect to address 173.194.192.109: Connection timed out
Trying 173.194.192.108...
telnet: connect to address 173.194.192.108: Connection timed out
Trying 2607:f8b0:4001:c0e::6d...
telnet: connect to address 2607:f8b0:4001:c0e::6d: Network is unreachable
```

**Comment by srenon** [comment]
Check with your server admin/support  to verifly if that port is block or open.. Base on the error message and that test that port seem to be block

**Comment by thagxt** [comment]
support says:

> I can confirm that the ports 465 are open in the server. I have also confirmed that the value of SMTP_BLOCK is set as 0.

**Comment by thagxt** [comment]
now if I try again with telnet it returns:

```
telnet smtp.gmail.com 465
Trying 64.233.183.109...
Connected to smtp.gmail.com.
Escape character is '^]'.
Connection closed by foreign host.
```

**Comment by thagxt** [comment]
Update:
Google just sent me an email asking me if I want to allow "Less secure app" did that backend is able to send "test mail". 

but Contact Form isn't working. I still recieve `We can't process your request right now. Sorry, that's all we know.`

**Comment by srenon** [comment]
You need to login to gmail and enabled "Less secure app" for it to work... follow the instruction on the popup

**Comment by thagxt** [comment]
already did. but the contact us form doesn't send emails. show me the error stated above.

**Comment by srenon** [comment]
Can you try placing a test order to see if email work there?

**Comment by thagxt** [comment]
password reset is working.
mail for orders works as well.

must be something with the contact form.
