### ISSUE TITLE
Plugin doesn't support PLAIN connection type to SMTP

### ISSUE THREAD

**Issue by maqlec** [magepal/magento2-gmailsmtpapp#26]
May I ask why you doesn't support this type of authentication?

**Comment by srenon** [comment]
@maqlec ... Please provide more information and I'll add it

**Comment by maqlec** [comment]
Sorry, I had titled this topic wrong.
Your plugin supports only encrypted connections like SSL, TLS. But some SMTP's doesn't support it (like mine). I suggest to make option SSL type: no SSL:)

It would be a solution for my problem :)

**Comment by srenon** [comment]
@maqlec ... Not 100% sure I understand, what server are you trying to connect to so I can review and provide a solution

**Comment by maqlec** [comment]
I figured out why it hasn't worked. Your plugin is fine but my server denied connections from localhost. Please look at my pull request https://github.com/magepal/magento2-gmailsmtpapp/pull/27 . Additional field 'name' submitted to Zend Smtp completely resolved my problem.
