### ISSUE TITLE
Does not work ...

### ISSUE THREAD

**Issue by MattDelac** [magepal/magento2-gmailsmtpapp#28]
Hello,

I found this idea awesome but I can't make it work !

I tried twice with the following credentials:
- SMTP with an email address from OVH (port 587) [I should use STARSSL thus I think it comes from this missing parameter]
- SMTP with a google account (port 465, I tried with "smtp.googlemail.com" and "smtp.gmail.com") but it does not work as well

Do you have any idea to solve this ?

I really think that this is a great plugin

Best

Matt

**Comment by srenon** [comment]
@MattDelac ... When you do a test from the config section what error message did you get?

**Comment by MattDelac** [comment]
@srenon 
"Result
Connection timed out"

**Comment by MattDelac** [comment]
@srenon 
5.7.14 <https://accounts.google.com/signin/continue?sarp=1&scc=1&plt=AKgnsbvh 5.7.14 BwT83JpyQFP_nZeLouulcw2b7n5nz7tNZ2qijJrsvn_5j0YEk3dNDIqF15wM5cMcIsUL25 5.7.14 wi2_sGntDtufZ5XfqmQCS9fNK3oMKb0g3sjl59ciYFpfX7RWdFrm0_GiyCWhkKMe-O2CFU 5.7.14 K9zktc4Gbia_OFqRvNDeYnDYr1ckysxwnokvK_sf0GXSKZFuJVFEZ24wJTi1wLB875NNjG 5.7.14 kBeiBsVkGYr2WoTNCHPqzOvnBCXn4> Please log in via your web browser and 5.7.14 then try again. 5.7.14 Learn more at 5.7.14 https://support.google.com/mail/answer/78754 v10sm34389339wji.29 - gsmtp

**Comment by srenon** [comment]
@MattDelac Please follow the instruction in that link

**Comment by MattDelac** [comment]
@srenon Thanks !

**Comment by MattDelac** [comment]
@srenon Do you think it will be possible to ass STARTLS in the "SSL type" parameter ?

**Comment by srenon** [comment]
I would have to do some research on this .... I could not find any example using Zend Framework with StartTLS (except for this issue https://framework.zend.com/issues/browse/ZF-10758)

I will need to review the code to see how this work 

vendor/magento/zendframework1/library/Zend/Mail/Protocol/Smtp.php

```
        // If a TLS session is required, commence negotiation
        if ($this->_secure == 'tls') {
            $this->_send('STARTTLS');
            $this->_expect(220, 180);
            if (!stream_socket_enable_crypto($this->_socket, true, STREAM_CRYPTO_METHOD_TLS_CLIENT)) {
                /**
                 * @see Zend_Mail_Protocol_Exception
                 */
                #require_once 'Zend/Mail/Protocol/Exception.php';
                throw new Zend_Mail_Protocol_Exception('Unable to connect via TLS');
            }
            $this->_ehlo($host);
        }
```

**Comment by bfsmith07** [comment]
I'm having a similar issue, but i'm getting the error "Could not open socket".  Any ideas?
