### ISSUE TITLE
Autoload error: 'MagePal_GmailSmtpApp' component already exists

### ISSUE THREAD

**Issue by cerebrumgit** [magepal/magento2-gmailsmtpapp#3]
Hello, good morning

As picture when installing the module via composer was shown the error

http://pasteboard.co/18gBSMAu.png

Autoload error: 'MagePal_GmailSmtpApp' component already exists

To solve the occurrence I delete the folder

/app/code/MagePal

**Comment by srenon** [comment]
Where is the extension located now, in vendor folder or app/code/ folder?

**Comment by cerebrumgit** [comment]
Hello

When did the installation for some reason it was created two folders

both

/app/code/MagePal
/vendor/magepal
