### ISSUE TITLE
Could not open socket

### ISSUE THREAD

**Issue by bfsmith07** [magepal/magento2-gmailsmtpapp#30]
I have tried both SSL and TLS. 
I have tried both smtp.gmail.com and smtp.googlemail.com
I have tried enabling "Allow less secure apps" in my gmail account

I am using this on a Fedora 24 box, fully updated.
PHP version 5.6.27
ZEND engine 2.6.0
Magento 2.1.2

Nothing seems to work, always get the same error "Could not open socket".  Am I missing something?  Please let me know if there's something else I should try to get this working.

Thanks.

**Comment by srenon** [comment]
@bfsmith07 ... check to see if you port is open .... see https://github.com/magepal/magento2-gmailsmtpapp/issues/24

**Comment by bfsmith07** [comment]
telnet smtp.gmail.com 465
Trying 2607:f8b0:4001:c15::6c...
Connected to smtp.gmail.com.
Escape character is '^]'.
Connection closed by foreign host.

**Comment by srenon** [comment]
Take a look at http://stackoverflow.com/questions/28433816/how-to-fix-could-not-open-socket-in-zend-mail-zend-framework-2

**Comment by hubaig** [comment]
Hi,

I have the same problem. I have Open SSL installed and enabled. 

$ telnet smtp.gmail.com 465
Trying 74.125.193.108...
Connected to smtp.gmail.com.
Escape character is '^]'.

OpenSSL support	enabled
OpenSSL Library Version	OpenSSL 1.0.1e-fips 11 Feb 2013
OpenSSL Header Version	OpenSSL 1.0.1e-fips 11 Feb 2013
Openssl default config	/etc/pki/tls/openssl.cnf

Is there any way I can find out what is causing this?

Regards,
Hussain

**Comment by srenon** [comment]
What does `php -r "mail('s@gmail.com', 'My Subject', 'test');"` return

**Comment by hubaig** [comment]
That does not return anything and I get the email in my inbox (SPAM folder)

**Comment by coresh** [comment]
### Helped for me: (solution for smtp servers (including gmail):

Zend/Mail/Protocol/Abstract.php:267  function _connect($remote)
```
// $this->_socket = @stream_socket_client($remote, $errorNum, $errorStr, self::TIMEOUT_CONNECTION);
$this->_socket = stream_socket_client($remote, $errorNum, $errorStr, self::TIMEOUT_CONNECTION);
```
for self-signed SSL certificates use:
```
        $ctx = stream_context_create(['ssl' => [
            'verify_peer'      => false,
            'verify_peer_name' => false
        ]]);
        $this->_socket = stream_socket_client($remote, $errorNum, $errorStr, self::TIMEOUT_CONNECTION, STREAM_CLIENT_CONNECT, $ctx);
```
vendor/magepal/magento2-gmailsmtpapp/Controller/Adminhtml/Test/Index.php:73
for chrome/chromium browsers,
during checking a connection, force email password:
// 'password' => $password,
'password' => 'yor email password',

**Comment by hubaig** [comment]
Can you please explain in detail how you fixed this issue?

**Comment by coresh** [comment]
@hubaig : Additional details added  to previsions comment. Is the current statement: pretty clear and understandable?

**Comment by truxxx** [comment]
I have the same issue:
OpenSSL support	enabled
OpenSSL Library Version	OpenSSL 1.0.1e-fips 11 Feb 2013
OpenSSL Header Version	OpenSSL 1.0.1e-fips 11 Feb 2013
Openssl default config	/etc/pki/tls/openssl.cnf

Telnet works, I have other 1.x Magento's on the same server using ASchroder Gmail SMTP extension, that works fine. Trying to find a solution for 2.x

I tried @coresh solution and that does nothing. Coresh you should update your comment to have a better location: vendor/magento/zendframework1/library/Zend/Mail/Protocol/Abstract.php:267 

Help!

**Comment by coresh** [comment]
@truxxx : comment - updated. Solution worked for me. Please try again attentively

**Comment by truxxx** [comment]
@coresh Thanks I missed the ctx step, however now i'm getting "Incorrect authentication data " when the credentials are correct.

**Comment by truxxx** [comment]
@coresh Thanks, I missed the ctx, however now i'm getting the error: "Incorrect authentication data " and I know my credentials are correct.

**Comment by coresh** [comment]
Try manually fix for testing purpose using browser (only for testing by browser)
Why? - Browser not correct updated input field:
```
vendor/magepal/magento2-gmailsmtpapp/Controller/Adminhtml/Test/Index.php:73
for chrome/chromium browsers,
during 'Sending test email', force email password like an example:
// 'password' => $password,
'password' => 'your email password',
```
For production usage should be: 'password' => $password,

**Comment by truxxx** [comment]
@coresh before I even posted I tried different browsers, I also tried setting the username and password 
manually in vendor/magepal/magento2-gmailsmtpapp/Controller/Adminhtml/Test/Index.php:73

First I just tried the password per your instructions, but then I tried the username as well. It always comes back with the same error, I tried different Gmail/Google Apps accounts as well.

**Comment by truxxx** [comment]
Is there some sort of error log I can check?

**Comment by coresh** [comment]
@truxxx  could you check another smtp server (e.g: your own smtp server) instead google smtp server and trace log?

**Comment by truxxx** [comment]
@coresh Thanks for the response!
I have removed this plugin and reinstalled it with composer.

Have your suggested edits be committed? I didn't need to change anything it already had the code when I looked at it.

Anyways I have tried with another SMTP host, bluehost, bluehost will allow me to send SSL or NON SSL however I get the same error with SSL: "Incorrect authentication data"

Without SSL I get this error:
Warning: stream_socket_client(): php_network_getaddresses: getaddrinfo failed: Name or service not known in public_html/sandbox/vendor/magento/zendframework1/library/Zend/Mail/Protocol/Abstract.php on line 272

I haven't had a chance to try it on the SMTP server that's on the local server itself, its not enabled by default and I have to change somethings around before and set it up before I can test it that way.

**Comment by srenon** [comment]
Take a look at http://stackoverflow.com/questions/6275535/php-error-php-network-getaddresses-getaddrinfo-failed-while-getting-informat ... try pinging the host

**Comment by coresh** [comment]
@truxxx, could you try again with php 7.*?

**Comment by pmagony** [comment]
The description states this can be used with "Other" SMTP. I'm trying to leverage GoDaddy smtp. Is this possible? I'm getting timeout requests on my efforts.

**Comment by srenon** [comment]
Can you provide the exact error message you are getting?

**Comment by pmagony** [comment]
@srenon sure, I've tried several configurations, using a Gmail account and Gmail settings, as well as GoDaddy settings and in both cases I've received the following error:

Result: Connection timed out

Gmail Settings: 
Localhost
Login
SSL
smtp.gmail.com
Port: 465
user / pass
Reply-to: No 
Return-path: No

Godaddy Settings: 
Localhost
Login
SSL
smtpout.secureserver.net
Port: 465
user / pass
Reply-to: No 
Return-path: No

**Comment by srenon** [comment]
@pmagony ... connection time out normally mean something is blocking the connect to gmail server. ( i have not use godaddy servers in years and back then you had to do "something special to send email") eg https://www.godaddy.com/help/specifying-an-email-address-for-the-php-form-mailer-508

Was Magento sending emails before installing this extension?

What is the output of the following command

`php -r "mail('s@gmail.com', 'My Subject', 'test');"`

`telnet smtp.gmail.com 465`

**Comment by bfsmith07** [comment]
Did anyone ever find a working solution?  I tried the fix from @coresh and it worked fine at first.  Now i'm getting a new error: Warning: stream_socket_client(): php_network_getaddresses: getaddrinfo failed: Name or service not known in vendor/magento/zendframework1/library/Zend/Mail/Protocol/Abstract.php on line 268.

**Comment by truxxx** [comment]
@coresh I'm using PHP Version 5.6.30, ill trying switching PHP version and let you know.

**Comment by truxxx** [comment]
@coresh I installed PHP Version 7.0.15, I'm having the same issues, I have even uninstalled the manual install and did a clean install through composer, still no go. Incorrect authentication data

**Comment by truxxx** [comment]
@coresh I ended up doing this: http://magento.stackexchange.com/questions/92860/magento-2-smtp-settings and now it works.

**Comment by coresh** [comment]
@truxxx Great!
