### ISSUE TITLE
Can we compatible with Mandrill extension? both rewrite Message model.

### ISSUE THREAD

**Issue by liangkuo** [magepal/magento2-gmailsmtpapp#32]
Please help this.
Mandrill extension.
https://store.ebizmarts.com/magemonkey-magento2.html

**Comment by srenon** [comment]
I had a idea that it would not be compatible with that extension.

Could you provide more information on how you are using Mandrill (does it send magento transaction email)?

**Comment by srenon** [comment]
I'm assuming this issue is fix, since you have not reply
