### ISSUE TITLE
Error on gmail login

### ISSUE THREAD

**Issue by tgsergiu** [magepal/magento2-gmailsmtpapp#33]
Hello,

First of all thanks for this great extension.
Unfortunatelly for me is not working. I get this erros:

(https://cloud.githubusercontent.com/assets/23265106/20454969/4cabb554-ae58-11e6-967b-ea1630090f6c.png)

Could you provide a solution? Google keeps sending me mail that someone has my password

Thanks!

**Comment by srenon** [comment]
@tgsergiu ... click on the first link in the error message  and follow the instructions

**Comment by tgsergiu** [comment]
Hi,

I did how you told me and i finally figured it out. The trick with the link is that it does not redirect in the good place. You need to go to google admin, and from there check the less secure apps (last option, the one that says Not Recommended)

The test email works, now the problem is that i do not receive emails on new orders, nor do the costumer. Where do i get it wrong? Is there another config to modify?

Thanks

**Comment by srenon** [comment]
@tgsergiu ... if you try to fill out the contact us page do you get the email?

**Comment by tgsergiu** [comment]
Yes, i do get the email in the contact page

**Comment by srenon** [comment]
So there is something wrong in the order checkout.... are you bcc-ing or cc-ing multiple email address in your system config?

**Comment by tgsergiu** [comment]
i do not know that... :(
Is it to much to ask to ask you to take a look? my email is gina.cornescu@gmail.com if you write me i will send the loin credentials.

**Comment by srenon** [comment]
@tgsergiu .... I would love to help... but if I break something then I going to have to fix it or a week from today something stop work (it was working today) so I still have to go fix it. 

So I will try to provide you with as much information as I can to fix your issue, but as a policy I only log into paying client sites.

**Comment by tgsergiu** [comment]
I understand completely, no problem, is ok. I will modify config settings and see what happens :)

**Comment by tgsergiu** [comment]
Hi @srenon now it works!
Thanks so much for the help and for this amazing code!
All good things done will come back somehow one day! :)

**Comment by srenon** [comment]
@tgsergiu .... what was the issue prevent order email from sending?

**Comment by tgsergiu** [comment]
Hi, the problem was ME. I did not complete every field correctly.
After i disabled Less secure apps from the admin console, i just needed to make a few changes in the Sales Emails. Now everything is good.
