### ISSUE TITLE
Configuration Setting not showing after manual installation 

### ISSUE THREAD

**Issue by Nym77** [magepal/magento2-gmailsmtpapp#36]
Dears, 
    I am trying to install this extension following the instruction in a Mac using MAMP php7 and magento 2.1

the installation is successful and the module is in config.php

    'MagePal_GmailSmtpApp' => 1,

if I go to tores -> Configuration -> Advanced -> System -> 
All i can see is just the following blank page 

![screen shot 2016-11-28 at 13 08 59](https://cloud.githubusercontent.com/assets/9418130/20667954/6a691d1e-b56c-11e6-8c88-501b148614d7.png)

[2016-11-28 12:32:35] main.CRITICAL: Class MagePal\GmailSmtpApp\Block\Adminhtml\System\Config\Version does not exist [] []
[2016-11-28 12:32:35] main.CRITICAL: Invalid block type: MagePal\GmailSmtpApp\Block\Adminhtml\System\Config\Version [] []

Am I missing something?

**Comment by srenon** [comment]
Can you check to see if this file exist https://github.com/magepal/magento2-gmailsmtpapp/blob/master/Block/Adminhtml/System/Config/Version.php

If manually installed, should be in 
app/code/MagePal/GmailSmtpApp/Block/Adminhtml/System/Config/Version.php

**Comment by Nym77** [comment]
@srenon Yes is there and is exactly the file that you mention

**Comment by srenon** [comment]
What mode are you running magento in?

see app/etc/env.php

```'MAGE_MODE' => 'developer',```

**Comment by Nym77** [comment]
'MAGE_MODE' => 'default',

**Comment by Nym77** [comment]
Just re-deply the module in developer mode and below you can find the stack trace. It is generated when I try to enter in Stores -> Configuration -> Advanced -> System ->

2 exception(s):
Exception #0 (Magento\Framework\Exception\LocalizedException): Invalid block type: MagePal\GmailSmtpApp\Block\Adminhtml\System\Config\Version
Exception #1 (ReflectionException): Class MagePal\GmailSmtpApp\Block\Adminhtml\System\Config\Version does not exist

Exception #0 (Magento\Framework\Exception\LocalizedException): Invalid block type: MagePal\GmailSmtpApp\Block\Adminhtml\System\Config\Version
#0 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Layout/Generator/Block.php(237): Magento\Framework\View\Layout\Generator\Block->getBlockInstance('MagePal\\GmailSm...', Array)
#1 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Layout.php(760): Magento\Framework\View\Layout\Generator\Block->createBlock('MagePal\\GmailSm...', 'adminhtml\\syste...', Array)
#2 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Layout.php(743): Magento\Framework\View\Layout->_createBlock('MagePal\\GmailSm...', 'adminhtml\\syste...', Array)
#3 /Applications/MAMP/htdocs/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(349): Magento\Framework\View\Layout->createBlock('MagePal\\GmailSm...', 'adminhtml\\syste...', Array)
#4 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Layout.php(973): Magento\Framework\View\Layout\Interceptor->createBlock('MagePal\\GmailSm...')
#5 /Applications/MAMP/htdocs/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(518): Magento\Framework\View\Layout->getBlockSingleton('MagePal\\GmailSm...')
#6 /Applications/MAMP/htdocs/magento2/vendor/magento/module-config/Block/System/Config/Form.php(330): Magento\Framework\View\Layout\Interceptor->getBlockSingleton('MagePal\\GmailSm...')
#7 /Applications/MAMP/htdocs/magento2/vendor/magento/module-config/Block/System/Config/Form.php(284): Magento\Config\Block\System\Config\Form->_initElement(Object(Magento\Config\Model\Config\Structure\Element\Field\Interceptor), Object(Magento\Framework\Data\Form\Element\Fieldset), 'system/gmailsmt...', '', '')
#8 /Applications/MAMP/htdocs/magento2/vendor/magento/module-config/Block/System/Config/Form.php(224): Magento\Config\Block\System\Config\Form->initFields(Object(Magento\Framework\Data\Form\Element\Fieldset), Object(Magento\Config\Model\Config\Structure\Element\Group), Object(Magento\Config\Model\Config\Structure\Element\Section))
#9 /Applications/MAMP/htdocs/magento2/vendor/magento/module-config/Block/System/Config/Form.php(170): Magento\Config\Block\System\Config\Form->_initGroup(Object(Magento\Config\Model\Config\Structure\Element\Group), Object(Magento\Config\Model\Config\Structure\Element\Section), Object(Magento\Framework\Data\Form))
#10 /Applications/MAMP/htdocs/magento2/vendor/magento/module-config/Block/System/Config/Form.php(456): Magento\Config\Block\System\Config\Form->initForm()
#11 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Element/AbstractBlock.php(658): Magento\Config\Block\System\Config\Form->_beforeToHtml()
#12 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Layout.php(542): Magento\Framework\View\Element\AbstractBlock->toHtml()
#13 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Layout.php(518): Magento\Framework\View\Layout->_renderBlock('system\\config\\f...')
#14 /Applications/MAMP/htdocs/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('system\\config\\f...')
#15 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('system\\config\\f...')
#16 /Applications/MAMP/htdocs/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('system\\config\\f...', true)
#17 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Element/AbstractBlock.php(499): Magento\Framework\View\Layout\Interceptor->renderElement('system\\config\\f...', true)
#18 /Applications/MAMP/htdocs/magento2/vendor/magento/module-config/view/adminhtml/templates/system/config/edit.phtml(22): Magento\Framework\View\Element\AbstractBlock->getChildHtml('form')
#19 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/Applications/M...')
#20 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Config\Block\System\Config\Edit), '/Applications/M...', Array)
#21 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Element/Template.php(279): Magento\Framework\View\Element\Template->fetchView('/Applications/M...')
#22 /Applications/MAMP/htdocs/magento2/vendor/magento/module-backend/Block/Template.php(104): Magento\Framework\View\Element\Template->_toHtml()
#23 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Element/AbstractBlock.php(659): Magento\Backend\Block\Template->_toHtml()
#24 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Layout.php(542): Magento\Framework\View\Element\AbstractBlock->toHtml()
#25 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Layout.php(518): Magento\Framework\View\Layout->_renderBlock('system.config.e...')
#26 /Applications/MAMP/htdocs/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('system.config.e...')
#27 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('system.config.e...')
#28 /Applications/MAMP/htdocs/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('system.config.e...', true)
#29 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('system.config.e...')
#30 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('content')
#31 /Applications/MAMP/htdocs/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('content')
#32 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('content')
#33 /Applications/MAMP/htdocs/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('content', true)
#34 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('content')
#35 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('admin.scope.col...')
#36 /Applications/MAMP/htdocs/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('admin.scope.col...')
#37 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('admin.scope.col...')
#38 /Applications/MAMP/htdocs/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('admin.scope.col...', true)
#39 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('admin.scope.col...')
#40 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('main.col')
#41 /Applications/MAMP/htdocs/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('main.col')
#42 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('main.col')
#43 /Applications/MAMP/htdocs/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('main.col', true)
#44 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('main.col')
#45 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('page.main.conta...')
#46 /Applications/MAMP/htdocs/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.main.conta...')
#47 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.main.conta...')
#48 /Applications/MAMP/htdocs/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.main.conta...', true)
#49 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('page.main.conta...')
#50 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('page.content')
#51 /Applications/MAMP/htdocs/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.content')
#52 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.content')
#53 /Applications/MAMP/htdocs/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.content', true)
#54 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('page.content')
#55 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('page.wrapper')
#56 /Applications/MAMP/htdocs/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
#57 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.wrapper')
#58 /Applications/MAMP/htdocs/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.wrapper', true)
#59 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('page.wrapper')
#60 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('backend.page')
#61 /Applications/MAMP/htdocs/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('backend.page')
#62 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('backend.page')
#63 /Applications/MAMP/htdocs/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('backend.page', true)
#64 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('backend.page')
#65 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('root')
#66 /Applications/MAMP/htdocs/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('root')
#67 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('root')
#68 /Applications/MAMP/htdocs/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('root', true)
#69 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Layout.php(938): Magento\Framework\View\Layout\Interceptor->renderElement('root')
#70 /Applications/MAMP/htdocs/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(492): Magento\Framework\View\Layout->getOutput()
#71 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Result/Page.php(243): Magento\Framework\View\Layout\Interceptor->getOutput()
#72 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Result/Layout.php(164): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#73 /Applications/MAMP/htdocs/magento2/var/generation/Magento/Backend/Model/View/Result/Page/Interceptor.php(193): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#74 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/App/Http.php(139): Magento\Backend\Model\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#75 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#76 /Applications/MAMP/htdocs/magento2/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#77 {main}

Exception #1 (ReflectionException): Class MagePal\GmailSmtpApp\Block\Adminhtml\System\Config\Version does not exist
#0 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/Code/Reader/ClassReader.php(19): ReflectionClass->__construct('MagePal\\GmailSm...')
#1 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/ObjectManager/Definition/Runtime.php(44): Magento\Framework\Code\Reader\ClassReader->getConstructor('MagePal\\GmailSm...')
#2 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(71): Magento\Framework\ObjectManager\Definition\Runtime->getParameters('MagePal\\GmailSm...')
#3 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('MagePal\\GmailSm...', Array)
#4 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Element/BlockFactory.php(45): Magento\Framework\ObjectManager\ObjectManager->create('MagePal\\GmailSm...', Array)
#5 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Layout/Generator/Block.php(257): Magento\Framework\View\Element\BlockFactory->createBlock('MagePal\\GmailSm...', Array)
#6 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Layout/Generator/Block.php(237): Magento\Framework\View\Layout\Generator\Block->getBlockInstance('MagePal\\GmailSm...', Array)
#7 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Layout.php(760): Magento\Framework\View\Layout\Generator\Block->createBlock('MagePal\\GmailSm...', 'adminhtml\\syste...', Array)
#8 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Layout.php(743): Magento\Framework\View\Layout->_createBlock('MagePal\\GmailSm...', 'adminhtml\\syste...', Array)
#9 /Applications/MAMP/htdocs/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(349): Magento\Framework\View\Layout->createBlock('MagePal\\GmailSm...', 'adminhtml\\syste...', Array)
#10 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Layout.php(973): Magento\Framework\View\Layout\Interceptor->createBlock('MagePal\\GmailSm...')
#11 /Applications/MAMP/htdocs/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(518): Magento\Framework\View\Layout->getBlockSingleton('MagePal\\GmailSm...')
#12 /Applications/MAMP/htdocs/magento2/vendor/magento/module-config/Block/System/Config/Form.php(330): Magento\Framework\View\Layout\Interceptor->getBlockSingleton('MagePal\\GmailSm...')
#13 /Applications/MAMP/htdocs/magento2/vendor/magento/module-config/Block/System/Config/Form.php(284): Magento\Config\Block\System\Config\Form->_initElement(Object(Magento\Config\Model\Config\Structure\Element\Field\Interceptor), Object(Magento\Framework\Data\Form\Element\Fieldset), 'system/gmailsmt...', '', '')
#14 /Applications/MAMP/htdocs/magento2/vendor/magento/module-config/Block/System/Config/Form.php(224): Magento\Config\Block\System\Config\Form->initFields(Object(Magento\Framework\Data\Form\Element\Fieldset), Object(Magento\Config\Model\Config\Structure\Element\Group), Object(Magento\Config\Model\Config\Structure\Element\Section))
#15 /Applications/MAMP/htdocs/magento2/vendor/magento/module-config/Block/System/Config/Form.php(170): Magento\Config\Block\System\Config\Form->_initGroup(Object(Magento\Config\Model\Config\Structure\Element\Group), Object(Magento\Config\Model\Config\Structure\Element\Section), Object(Magento\Framework\Data\Form))
#16 /Applications/MAMP/htdocs/magento2/vendor/magento/module-config/Block/System/Config/Form.php(456): Magento\Config\Block\System\Config\Form->initForm()
#17 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Element/AbstractBlock.php(658): Magento\Config\Block\System\Config\Form->_beforeToHtml()
#18 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Layout.php(542): Magento\Framework\View\Element\AbstractBlock->toHtml()
#19 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Layout.php(518): Magento\Framework\View\Layout->_renderBlock('system\\config\\f...')
#20 /Applications/MAMP/htdocs/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('system\\config\\f...')
#21 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('system\\config\\f...')
#22 /Applications/MAMP/htdocs/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('system\\config\\f...', true)
#23 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Element/AbstractBlock.php(499): Magento\Framework\View\Layout\Interceptor->renderElement('system\\config\\f...', true)
#24 /Applications/MAMP/htdocs/magento2/vendor/magento/module-config/view/adminhtml/templates/system/config/edit.phtml(22): Magento\Framework\View\Element\AbstractBlock->getChildHtml('form')
#25 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/Applications/M...')
#26 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Config\Block\System\Config\Edit), '/Applications/M...', Array)
#27 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Element/Template.php(279): Magento\Framework\View\Element\Template->fetchView('/Applications/M...')
#28 /Applications/MAMP/htdocs/magento2/vendor/magento/module-backend/Block/Template.php(104): Magento\Framework\View\Element\Template->_toHtml()
#29 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Element/AbstractBlock.php(659): Magento\Backend\Block\Template->_toHtml()
#30 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Layout.php(542): Magento\Framework\View\Element\AbstractBlock->toHtml()
#31 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Layout.php(518): Magento\Framework\View\Layout->_renderBlock('system.config.e...')
#32 /Applications/MAMP/htdocs/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('system.config.e...')
#33 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('system.config.e...')
#34 /Applications/MAMP/htdocs/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('system.config.e...', true)
#35 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('system.config.e...')
#36 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('content')
#37 /Applications/MAMP/htdocs/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('content')
#38 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('content')
#39 /Applications/MAMP/htdocs/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('content', true)
#40 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('content')
#41 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('admin.scope.col...')
#42 /Applications/MAMP/htdocs/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('admin.scope.col...')
#43 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('admin.scope.col...')
#44 /Applications/MAMP/htdocs/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('admin.scope.col...', true)
#45 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('admin.scope.col...')
#46 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('main.col')
#47 /Applications/MAMP/htdocs/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('main.col')
#48 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('main.col')
#49 /Applications/MAMP/htdocs/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('main.col', true)
#50 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('main.col')
#51 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('page.main.conta...')
#52 /Applications/MAMP/htdocs/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.main.conta...')
#53 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.main.conta...')
#54 /Applications/MAMP/htdocs/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.main.conta...', true)
#55 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('page.main.conta...')
#56 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('page.content')
#57 /Applications/MAMP/htdocs/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.content')
#58 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.content')
#59 /Applications/MAMP/htdocs/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.content', true)
#60 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('page.content')
#61 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('page.wrapper')
#62 /Applications/MAMP/htdocs/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
#63 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.wrapper')
#64 /Applications/MAMP/htdocs/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.wrapper', true)
#65 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('page.wrapper')
#66 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('backend.page')
#67 /Applications/MAMP/htdocs/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('backend.page')
#68 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('backend.page')
#69 /Applications/MAMP/htdocs/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('backend.page', true)
#70 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('backend.page')
#71 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('root')
#72 /Applications/MAMP/htdocs/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('root')
#73 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('root')
#74 /Applications/MAMP/htdocs/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('root', true)
#75 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Layout.php(938): Magento\Framework\View\Layout\Interceptor->renderElement('root')
#76 /Applications/MAMP/htdocs/magento2/var/generation/Magento/Framework/View/Layout/Interceptor.php(492): Magento\Framework\View\Layout->getOutput()
#77 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Result/Page.php(243): Magento\Framework\View\Layout\Interceptor->getOutput()
#78 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/View/Result/Layout.php(164): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#79 /Applications/MAMP/htdocs/magento2/var/generation/Magento/Backend/Model/View/Result/Page/Interceptor.php(193): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#80 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/App/Http.php(139): Magento\Backend\Model\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#81 /Applications/MAMP/htdocs/magento2/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#82 /Applications/MAMP/htdocs/magento2/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#83 {main}

**Comment by caseybarsness** [comment]
I am having the same issue.  
`PHP Fatal error:  Uncaught Error: Class 'MagePal\\GmailSmtpApp\\Block\\Adminhtml\\System\\Config\\Version' not found in /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php`

I have verified that the file exists and has the correct content.

**Comment by truxxx** [comment]
I did a manual install and I had a simular issue, the problem was this:

In the Readme it tell you to create the folder 
Magepal/SmtpApp

It needs to be 
MagePal/GamilSmtpApp/

I was getting this error:
[2016-12-11 16:59:14] main.CRITICAL: Class MagePal\GmailSmtpApp\Block\Adminhtml\System\Config\Version does not exist [] []
[2016-12-11 16:59:14] main.CRITICAL: Invalid block type: MagePal\GmailSmtpApp\Block\Adminhtml\System\Config\Version [] []

Now I see the config

**Comment by srenon** [comment]
@caseybarsness .... What version of magento2.x, php, and OS are you using?
