### ISSUE TITLE
E-mail test works but nothing else is sending

### ISSUE THREAD

**Issue by jeffreytu** [magepal/magento2-gmailsmtpapp#37]
Hello. I have just installed this extension and set up my configuration for Gmail apps. I did the test e-mail and it works, but actual transaction e-mails aren't being sent. Is there an additional configuration I need to set somewhere? Thanks.

**Comment by srenon** [comment]
Did you try testing using a "contact us" form.

Also try clearing cache and make sure your email setting is correctly configure for each (sales email and contact form).

**Comment by jeffreytu** [comment]
I think clearing the cache was the issue. I tested the contact us and it works, and I also see the transaction e-mails now. Thanks.
