### ISSUE TITLE
Warning: stream_socket_enable_crypto(): Peer certificate CN

### ISSUE THREAD

**Issue by jeffreytu** [magepal/magento2-gmailsmtpapp#38]
Hello. I was able to get this extension to work for a few days but now no e-mails are being sent. When I try the test send an e-mail, I get:

```
Warning: stream_socket_enable_crypto(): Peer certificate CN=`*.somehost.host' did not match expected CN=`smtp.gmail.com' in /home/mydir/public_html/vendor/magento/zendframework1/library/Zend/Mail/Protocol/Smtp.php on line 206
```

I'm not entirely sure what the above means. If anyone can help me on this, that would be great.

**Comment by srenon** [comment]
@jeffreytu .... are you still having issues?

**Comment by NotFrom** [comment]
Hi 
I'm getting the same issue:
Warning: stream_socket_enable_crypto(): Peer certificate CN=`<myhostname>' did not match expected CN=`<my SMTP Host setting>' in ../public_html/vendor/magento/zendframework1/library/Zend/Mail/Protocol/Smtp.php on line 206

Tried using basic SMTP connection into office 365.

Thanks,
Peter
