### ISSUE TITLE
Can this app be used as send-only email from website without any other server such Postfix ?

### ISSUE THREAD

**Issue by Jacob-Wilsons** [magepal/magento2-gmailsmtpapp#39]
Can this app be used as send-only email from website without any other server such Postfix ?

I have 2 domains hosted on Godaddy, Godaddy has my DNS.

In DNS I pointed both webistes to my VPS ip and installed two Magento 2 websites.

I pointed mail to yandex, so my email for my domains are via yandex mail servers.

I installed this magento2-gmailsmtpapp to both of my magento 2 websites. Configured everething and each domain sends emails as expected.

As an experiment I removed Postfix and Dovecot from my vps but this app continue to work on each of websites as usual ! How that can be? Is this app acts as a send-only mail server?

I scanned the ports and looks like port ( 111 portmapper, rpcbind ) is open, is this related to this app?

Questions 1: Can  this app  be used as send-only emails without Postfix?

Question 2: In this app can I add DKIM or SPF to each of domains?  Thank you

![1](https://cloud.githubusercontent.com/assets/24421322/20951284/c05755e2-bbd9-11e6-8aa2-78327a8d53bc.jpg)

My config: 
Centos 7 
PHP 7
Mysql 5.6
Apache 2.4

**Comment by srenon** [comment]
Can you send mail using native php "mail" function?

Please see Zend smtp for info  https://framework.zend.com/manual/2.4/en/modules/zend.mail.smtp.options.html
