### ISSUE TITLE
README.md unclear

### ISSUE THREAD

**Issue by zelfkoelman** [magepal/magento2-gmailsmtpapp#4]
Dear ms/sr,
Could you be more clear on how to install this plugin on a downloaded magento installation?

1. I have added to the _composer.json_ file the following line: `"magepal/magento2-gmailsmtpapp": "1.0.3"`
2. At _System > Web Setup Wizard > Component Manager_ nothing is visible after _sync_

**Comment by srenon** [comment]
@zelfkoelman ... Let me know if you still having issue

**Comment by zelfkoelman** [comment]
isn't is _GmailSmtpApp_ instead of _GmailSmptApp_ 
and _MagePal_GmailSmtpApp_ instead of _MagePal_GmailSmptApp_ ?

**Comment by zelfkoelman** [comment]
Thanks, manual installation successful!

Perhaps it is helpful for some of us to add that the _php -f bin/magento module:enable --clear-static-content MagePal_GmailSmtpApp_ command should be run from the magento root folder.

**Comment by zelfkoelman** [comment]
Also tried the composer approach:

getting an error: [RuntimeException]                                                                                                                                                                      
 `Failed to clone https://*****ce0****************258****:***@github.com/magepal/magento2-gmailsmtpapp.git, git was not found, check that it is installed and in your PATH env.  
  sh: 1: git: not found`

**Comment by srenon** [comment]
@zelfkoelman .. thanks for pointing out the typo
