### ISSUE TITLE
Test email is working but no other emails send.

### ISSUE THREAD

**Issue by TechNix66** [magepal/magento2-gmailsmtpapp#41]
Today I installed the extension and after configuration I'm able to send succesfully the test email.
Unfortunately no emails are send via the Contact Form and also no Transactional Emails.

Cleaned the cache many times but nothing helps.

Strange thing is that the GUI shows the message 'Thanks for contacting us with your comments and questions. We'll respond to you very soon.' after the Contact Form is submitted.

Before I installed this exstension I had the standard email option enabled and saw mails initiated. This gives me the impression that in priciple Magento itself is configured properly, /home/xxxxxx/.php/php-mail.log shows:
`[03-Jan-2017 21:03:47 UTC] mail() on [/home/xxxxxxxxxx/public_html/vendor/magento/zendframework1/library/Zend/Mail/Transport/Sendmail.php:106]: To: xxxxxxxxxx -- Headers: From: xxxxxxxxxx Reply-To: xxxxxxxxxx Content-Type: text/plain; charset=utf-8 Content-Transfer-Encoding: quoted-printable Content-Disposition: inline MIME-Version: 1.0`

My configuration is:
Gmail Smtp App v1.4.0
Magento version 2.1.3
PHP Version 7.0.13

**Comment by TechNix66** [comment]
I just checked my logs (Magento in Developer-mode) and no errors are reported in system.log and debug.log.

**Comment by srenon** [comment]
What email provider are you using (gmail)?

**Comment by TechNix66** [comment]
I'm using a smpt-server at iXL hosting with the settings:

![settings](https://cloud.githubusercontent.com/assets/24798821/21656931/828d4106-d2c0-11e6-8ef9-447c216627af.jpg)

**Comment by TechNix66** [comment]
Finally I found the root cause of this problem. It was related to an incorrect configuration of the MX record of my test server.
