### ISSUE TITLE
Will not install: composer require magepal/magento2-gmailsmtpapp fails

### ISSUE THREAD

**Issue by deckside** [magepal/magento2-gmailsmtpapp#42]
when I run 
composer require magepal/magento2-gmailsmtpapp

I get the following error
bitnami@ip-172-31-17-133:~$ composer require magepal/magento2-gmailsmtpapp
Using version ^1.4 for magepal/magento2-gmailsmtpapp
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for magepal/magento2-gmailsmtpapp ^1.4 -> satisfiable by magepal/magento2-gmailsmtpapp[1.4.0].
    - magepal/magento2-gmailsmtpapp 1.4.0 requires magento/module-backend 100.0.*|100.1.* -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, deleting ./composer.json.

Magento 2.1.2, BitNami, AWS, (fresh install)

**Comment by srenon** [comment]
The issue seem to be cause by 

>magento/module-backend 100.0.|100.1. -> no matching package found.

What "version" number is in vendor/magento/module-backend/composer.json

**Comment by deckside** [comment]
This is the contents of vendor/magento/module-backend/composer.json

{
    "name": "magento/module-backend",
    "description": "N/A",
    "require": {
        "php": "~5.6.5|7.0.2|7.0.4|~7.0.6",
        "magento/module-store": "100.1.*",
        "magento/module-directory": "100.1.*",
        "magento/module-developer": "100.1.*",
        "magento/module-eav": "100.1.*",
        "magento/module-theme": "100.1.*",
        "magento/module-reports": "100.1.*",
        "magento/module-sales": "100.1.*",
        "magento/module-quote": "100.1.*",
        "magento/module-catalog": "101.0.*",
        "magento/module-user": "100.1.*",
        "magento/module-security": "100.1.*",
        "magento/module-backup": "100.1.*",
        "magento/module-customer": "100.1.*",
        "magento/module-translation": "100.1.*",
        "magento/module-require-js": "100.1.*",
        "magento/module-config": "100.1.*",
        "magento/framework": "100.1.*"
    },
    "type": "magento2-module",
    "version": "100.1.1",
    "license": [
        "OSL-3.0",
        "AFL-3.0"
    ],
    "autoload": {
        "files": [
            "registration.php"
        ],
        "psr-4": {
            "Magento\\Backend\\": ""
        }
    }
}

**Comment by deckside** [comment]
I have now managed to get past the problem I was having but now I have a new problem.

When I run 
composer require magepal/magento2-gmailsmtpapp
 I get a message 
*****
Using version ^1.4 for magepal/magento2-gmailsmtpapp
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing magepal/magento2-gmailsmtpapp (1.4.0) Downloading: 100%
Package fabpot/php-cs-fixer is abandoned, you should avoid using it. Use friendsofphp/php-cs-fixer instead.
Writing lock file
Generating autoload files
root@ip-172-31-23-208:/opt/bitnami/apps/magento/htdocs# y
y: command not found

**********

If I try and run the next command  
php -f bin/magento module:enable --clear-static-content MagePal_GmailSmtpApp
I get an error

**********
root@ip-172-31-23-208:/opt/bitnami/apps/magento/htdocs# php -f bin/magento module:enable --clear-static-content MagePal_GmailSmtpApp
Autoload error: Module 'MagePal_GmailSmtpApp' from '/opt/bitnami/apps/magento/htdocs/app/code/MagePal/GmailSmtpApp' has been already defined in '/opt/bitnami/apps/magento/htdocs/vendor/magepal/magento2-gmailsmtpapp'.root@ip-172-31-23-208:/opt/bitnami/apps/magento/htdocs#
**************

If I try to get to the website I get this error

Module 'MagePal_GmailSmtpApp' from '/opt/bitnami/apps/magento/htdocs/app/code/MagePal/GmailSmtpApp' has been already defined in '/opt/bitnami/apps/magento/htdocs/vendor/magepal/magento2-gmailsmtpapp'.

******************************************

Any help would be appreciated

Thank you

**Comment by srenon** [comment]
@deckside ... you seem to have installed it using both composer and manually.

Does these paths exist?

> app/code/MagePal/GmailSmtpApp

and

> vendor/magepal/magento2-gmailsmtpapp

if yes then move it "app/code/MagePal/GmailSmtpApp" to your home dir and try again

**Comment by deckside** [comment]
My Bad

I was doing both manual and composer installs.

Getting use to Magento 2 is taking time

Thank you for your help

**Comment by carlzuzart** [comment]
Can you please advise how you resolved this issue as I am facing the same thing and dont know what i am doing wrong. Seem to be going round in circles at this point

**Comment by srenon** [comment]
@carlzuzart ... What error are you getting?

**Comment by carlzuzart** [comment]
exact same error 
carl@ubuntu:~$ composer require magepal/magento2-gmailsmtpapp
Using version ^1.4 for magepal/magento2-gmailsmtpapp
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - magepal/magento2-gmailsmtpapp 1.4.1 requires magento/module-backend 100.0.                                                                                                                               *|100.1.* -> no matching package found.
    - magepal/magento2-gmailsmtpapp 1.4.0 requires magento/module-backend 100.0.                                                                                                                               *|100.1.* -> no matching package found.
    - Installation request for magepal/magento2-gmailsmtpapp ^1.4 -> satisfiable                                                                                                                                by magepal/magento2-gmailsmtpapp[1.4.0, 1.4.1].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your min                                                                                                                               imum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more det                                                                                                                               ails.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further commo                                                                                                                               n problems.

Installation failed, deleting ./composer.json.

**Comment by srenon** [comment]
How did you install Magento ... GitHub or composer?

Is the Magento folder in "app/code/Magento" or "vender/magento"?

**Comment by carlzuzart** [comment]
its in /var/www/html/app/code/MagePal

**Comment by carlzuzart** [comment]
and im on ubuntu 16.04 lts with Lamp stack

**Comment by srenon** [comment]
Anything that installed using composer will be located in the "vendor" folder. 

If you manually installed it in "app/code/MagePal" then you should not be trying to install it using composer.

If you copy the files correctly to "app/code/MagePal" then all you will need to do is run ```php magento/bin setup:upgrade```

How did you install magento, using composer/download or github clone?

**Comment by carlzuzart** [comment]
i downloaded it and then extracted and copy pasted it. Triued running the command this is what i got
carl@ubuntu:~$ sudo php magento/bin setup:upgrade
Could not open input file: magento/bin

**Comment by srenon** [comment]
Are you in the Magento root dir (web root)?

Type "pwd" to see where you are

**Comment by carlzuzart** [comment]
carl@ubuntu:~$ pwd
/home/carl
carl@ubuntu:~$

**Comment by carlzuzart** [comment]
Magento is installed in /var/www/html/

**Comment by srenon** [comment]
You need to run that command from Magento root dir

**Comment by vfpgawarrior** [comment]
> I have now managed to get past the problem I was having but now I have a new problem.
> 
> When I run
> composer require magepal/magento2-gmailsmtpapp
> I get a message
> 
> Using version ^1.4 for magepal/magento2-gmailsmtpapp
> ./composer.json has been updated
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Package operations: 1 install, 0 updates, 0 removals
> 
> * Installing magepal/magento2-gmailsmtpapp (1.4.0) Downloading: 100%
>   Package fabpot/php-cs-fixer is abandoned, you should avoid using it. Use friendsofphp/php-cs-fixer instead.
>   Writing lock file
>   Generating autoload files
>   root@ip-172-31-23-208:/opt/bitnami/apps/magento/htdocs# y
>   y: command not found
> 
> If I try and run the next command
> php -f bin/magento module:enable --clear-static-content MagePal_GmailSmtpApp
> I get an error
> 
> root@ip-172-31-23-208:/opt/bitnami/apps/magento/htdocs# php -f bin/magento module:enable --clear-static-content MagePal_GmailSmtpApp
> Autoload error: Module 'MagePal_GmailSmtpApp' from '/opt/bitnami/apps/magento/htdocs/app/code/MagePal/GmailSmtpApp' has been already defined in '/opt/bitnami/apps/magento/htdocs/vendor/magepal/magento2-gmailsmtpapp'.root@ip-172-31-23-208:/opt/bitnami/apps/magento/htdocs#
> 
> If I try to get to the website I get this error
> 
> Module 'MagePal_GmailSmtpApp' from '/opt/bitnami/apps/magento/htdocs/app/code/MagePal/GmailSmtpApp' has been already defined in '/opt/bitnami/apps/magento/htdocs/vendor/magepal/magento2-gmailsmtpapp'.
> 
> Any help would be appreciated
> 
> Thank you

how did you managed to get past the problem, as i am hvaing the same issue, please help!

**Comment by srenon** [comment]
@vfpgawarrior ... To my knowledge, Bitnami manually install the extension in ``app/code``, which mean if you want to install using composer you will have to delete the other version in ``app/code/MagePal/GmailSmtpApp``

>Hence this error msg 
'/opt/bitnami/apps/magento/htdocs/app/code/MagePal/GmailSmtpApp' has been already defined in '/opt/bitnami/apps/magento/htdocs/vendor/magepal/magento2-gmailsmtpapp'.
