### ISSUE TITLE
Can not install it on Magento version 2.1.2 

### ISSUE THREAD

**Issue by key-dev** [magepal/magento2-gmailsmtpapp#44]
Hi there,
I am unable to install it on Magento 2.1.2.
I am using this command.
composer require magepal/magento2-gmailsmtpapp

Please help

**Comment by srenon** [comment]
Without more information, it is next to impossible to provide a solution:

What happens after you enter the above command?

What error message are you getting?

**Comment by key-dev** [comment]
Thanks for getting back to me.
When i run that command this happens via SSH using putty.
![error-install](https://cloud.githubusercontent.com/assets/17259817/21818641/724fbc0a-d78a-11e6-9772-fcec0d0fa6e5.jpg)

Thanks in advance.

**Comment by srenon** [comment]
I don't think the issue is caused by this module.

I would suggest you try creating a backup of the site, then try to install a random free M2 and see if still getting an error.

Did you recently upgrade from 2.1.1?

**Comment by key-dev** [comment]
It worked using zip package and doing setup upgrade. But the error remained using composer.
Well! fixed it.
Thanks a lot
