### ISSUE TITLE
Password missing from settings

### ISSUE THREAD

**Issue by deckside** [magepal/magento2-gmailsmtpapp#45]
We have noticed the password drops out of the settings if the server is rebooted.

Is there a way of having the server store the password so it remains after a reboot?

**Comment by deckside** [comment]
After more testing its not the reboot that removes the password.

Any idea why the password drops out occassionally

**Comment by srenon** [comment]
@deckside 

What version of magento are you running?

The password is stored in core_config_data table

Could you provide more information on why you think it "drops out"?

**Comment by deckside** [comment]
I cannot replicate the problem.
Magneto 2.1.3 
This morning I sent a copy of an order and the error was incorrect password.

When I went to the admin console and looked at the setting the ***** were missing from the password.

I re-entered the password and its working again.

I just looked in core_config_data table and I cannot see a reference to the password.

**Comment by srenon** [comment]
@deckside ... is the value blank or you can not find the path for `system/gmailsmtpapp/username`?

**Comment by deckside** [comment]
I have found all the correct details in the core_config_data table and now I see the password is in there and it looks like its encrypted. 

If it stops again I will look in the table first to see if the data is still there.
