### ISSUE TITLE
Multisotre:  Mail send from backend(change status, comments) are send with bad domain

### ISSUE THREAD

**Issue by dezzer** [magepal/magento2-gmailsmtpapp#49]
Hello,
We have setup Magento2 with Multistore on two saperate domains with gmailsmtpapp.
If client make order from domain1.com then mail came from domain1.com ( this behavior is OK.)
But if Administrator log to backend http://domain2.com/admin/ and navigate to orders and change somthing in customer order from domain1.com then client get mail from domain2.com(witch administrator is logged) ( this behavior is bad).

I think sending e-mail to customer from backends should be independend on domain where administrator is log in. Customer should get mail from domain1.com where he make order.

What do you think about this?

**Comment by srenon** [comment]
@dezzer ... Is it possible for you to disable this module, then follow the same step in core magetno and let me know if core magento behave differently?

**Comment by srenon** [comment]
@dezzer ... in store -> config, did you enter two different email credential for both store (for domain1.com and domain2.com)?

**Comment by dezzer** [comment]
@srenon in store -> config > system>Gmail/google apps Pro for each domain i have different credential.
( in 15min i will check with disable module)

**Comment by dezzer** [comment]
@srenon the same situation without gmailsmtpapp.

**Comment by srenon** [comment]
@dezzer ... did you check https://github.com/magento/magento2/issues to see if this issue is reported

**Comment by dezzer** [comment]
@srenon i found similar problem https://github.com/magento/magento2/issues/8117#issuecomment-272242715

i use "temporary" patch: https://github.com/magento/magento2/issues/8117#issuecomment-272242715

and its work but with disabled gmailsmtpapp

with enabled mail are not sending.

**Comment by srenon** [comment]
@dezzer ... I don't think that code should affect this module, after enabling did you run `php bin/magento setup:upgrade`?

**Comment by dezzer** [comment]
@srenon yes i did. When i go to order and fill "Comment" form and check "Notify Customer by Email" then i get error "incorrect envelope address"

**Comment by srenon** [comment]
Does the frontend still work?

You can debug by checking the values below

	if(isset($this->templateVars['store'])){
		$scope_id = $this->templateVars['store']->getId();
		$result = $this->_senderResolver->resolve($from, $scope_id);
                // check to see what the output of $result['email'], $result['name'] with and without this code

	}else{
		$result = $this->_senderResolver->resolve($from);
	}

**Comment by dezzer** [comment]
@srenon before debug i check frontend ,and its work.
I made order in domain1.com and after that i login to domain1.com/admin and sent comment with checked "Notify Customer by Email" to customer and its work. after that i login to domain2.com/admin and do the same but i get error:  incorrect envelope addres

**Comment by QuentinHK** [comment]
Hi, I'm facing the same issue.
@dezzer did you find any work around, please?

**Comment by srenon** [comment]
@QuentinHK ... I will look into this shortly

**Comment by dondezo** [comment]
@QuentinHK Unfortunately not, sorry for delay in my answer.

**Comment by srenon** [comment]
I'm going to close this since they are multiple issues open for the same problem ... 

https://github.com/magepal/magento2-gmailsmtpapp/issues/75

https://github.com/magento/magento2/issues/11695
