### ISSUE TITLE
not compatible with PHP 7?

### ISSUE THREAD

**Issue by robbiefowler** [magepal/magento2-gmailsmtpapp#52]
Could not find package magepal/magento2-gmailsmtpapp at any version matchin
  g your PHP version 7.1.2.0

**Comment by srenon** [comment]
@robbiefowler ... I will review and update the [composer.json](https://github.com/magepal/magento2-gmailsmtpapp/blob/master/composer.json) "require" section shortly

**Comment by srenon** [comment]
@robbiefowler ... did you install magento using composer? 

Magento seem to be using the same php requirement as this module see https://github.com/magento/magento2/blob/develop/composer.json#L11

**Comment by robbiefowler** [comment]
yes I ran the command `composer require magepal/magento2-gmailsmtpapp` and got the error as above.  It would not install. I have installed it manually but having block ports issues so not sure if it will work

**Comment by srenon** [comment]
Since Magento technically don't support 7.1.2.0, removing the php requirement or adding this new version can only cause more harm than good (in term of me support this module).

One quick solution would be to fork this module and update the compose.json 


>composer config repositories.MyRepoHere-gmailsmtpapp git git@github.com:MyRepoHere/magento2-gmailsmtpapp.git

>composer require MyRepoHere/magento2-gmailsmtpapp:master
