### ISSUE TITLE
Invalid Sender Data

### ISSUE THREAD

**Issue by InternetMedicineMan** [magepal/magento2-gmailsmtpapp#54]
Previous issue was I couldn't complete orders because of an invalid "Mail FROM" error coming back from Amazon. I fixed that issue by just using Google Apps, so that no verification was needed.

But with Google Apps I cannot verify customers. Our store is set that new customers are just pending and must be approved since it's primarily a Wholesale site. So now when I click to approve a customer it emails that customer that their account has been approved. But I can't approve any accounts because it comes back "Invalid Sender Data" when trying to send the email.

So with Amazon SES everything works excepts orders. With Google Apps Email, everything works except approving customers. So I guess we can have a store that doesn't allow orders, or doesn't allow customers. LOL

**Comment by InternetMedicineMan** [comment]
I may have spoke too soon, it appears this issue persists even with this extension turned off. There is a different problem. Sorry.

**Comment by InternetMedicineMan** [comment]
Using the Pending Registration Module from Itoris. Should have known it would be the culprit. It was broken on upgrade which of course they required to pay again to get the update since their "support" doesn't even cover a year (4 months of support who does that). And now the module won't even let a customer log in. Frustrating.

**Comment by srenon** [comment]
I used their module once on a major project and I feel like I spend more time debugging and fixing issues than I spend on the project.

**Comment by InternetMedicineMan** [comment]
I'm starting to feel the same way but didn't see any alternatives for the extensions I needed.
