### ISSUE TITLE
Config for specific store does not work

### ISSUE THREAD

**Issue by mfortin** [magepal/magento2-gmailsmtpapp#55]
The default, global, config works as expected, I can send email.
When I specify a different user and password for one specific website, emails do not go out and I get an invalid username/password error. I am 100% sure about by username and password as I tested them in the global config and it works. Also, if both account have the same password, it works.

The error I get:

5.7.8 Username and Password not accepted. Learn more at 5.7.8 https://support.google.com/mail/?p=BadCredentials n9sm12222140wrn.40 - gsmtp

**Comment by srenon** [comment]
@mfortin ... I think this should be a core bug see https://github.com/magento/magento2/issues/8591 but what version of magento, php and OS are you using

**Comment by mfortin** [comment]
Don't think it is. 

Magento 2.1.2 on ubuntu with php 7.

The store value seems to be fetched from getParams, however, I do not see a store value in the request...

**Comment by srenon** [comment]
You may be correct, give me a few to review this because "store_id" should be numeric while "store" is alph-numeric code 

Block/Adminhtml/System/Config/TestButton.php
```
   public function getAdminUrl(){
        return $this->_urlBuilder->getUrl('magepalGmailsmtpapp/test', ['store' => $this->_request->getParam('store')]);
    }
```


Controller/Adminhtml/Test/Index.php
```
$store_id = $request->getParam('store', null);
```

**Comment by mfortin** [comment]
While you're at it, the test button only does a basic email sending test. It does not try to validate the returnpath and reply-to settings. I wanted to check the effect of each but I had to do some test case using the frontend to validate. No big issue, just a "nice to have" feature. :D

**Comment by zack6849** [comment]
If you guys want to bring more attention to my bug report, it'd be appreciated, nobody from the magento team has even acknowledged it in almost a month, a few +1's or comments confirming you also share the same problem may get them to take a closer look

**Comment by s00071609** [comment]
I am having similar issues. There are two store websites in one installation. When shipment is created for Store 2, email assigned to Store 1 gets used to send the email. I have had this issue from start, may be around a year. I just installed latest version but this issue did not go

**Comment by srenon** [comment]
@s00071609 .... I will review this shortly. 

Did you try disabling this module to see if this is a module or core Magento issue? Take a look at https://github.com/magento/magento2/issues/6954

Can you provide more information on you multi-store setup, so that I can replicate this enviroment to figure out the issue

**Comment by s00071609** [comment]
even if i disable this module, it does not seem to be disabled.

It works for sales order, and other email but not with shipment email. Its two stores running on same magento installation via htaccess code.

**Comment by srenon** [comment]
Did you flush the cache?

**Comment by s00071609** [comment]
Problem is after i disable and clear cache nothing changes. But when i remove the account detail from this extension and save, no emails get sent because there is no email setup and as i am using zoho mail - i guess magento does not support it.

**Comment by srenon** [comment]
@s00071609 @mfortin ... Are you still having this issue? Can I close this ticket?

**Comment by s00071609** [comment]
@srenon Yes this issue has not been resolved.

**Comment by mfortin** [comment]
Yes, still having the same issues. Works great using default configs, when setting up alternate configs for a specific view, it does not work as expected.

**Comment by QuentinHK** [comment]
Same issue here, having 2 stores with 2 domains. Sales orders confirmation emails are sent using the correct domain, but shipment notification emails are sent using the default email (main domain).

**Comment by srenon** [comment]
I'm going to close this since they are multiple issues open for the same problem ... 

https://github.com/magepal/magento2-gmailsmtpapp/issues/75

Please upvote this issue  - https://github.com/magento/magento2/issues/11695
