### ISSUE TITLE
NOT AN ISSUE...

### ISSUE THREAD

**Issue by spyrule** [magepal/magento2-gmailsmtpapp#58]
Hello,

Just thought I'd suggest to whoever manages this repo, that this extension works perfectly with Microsoft Office365. 
Notes to make it work:
Auth Method: Login
SSL Type: TLS
SMTP Host: smtp.office365.com
Port: 587
Username: donotreply@yourdomain.com (replace donotreply with an ACTUAL licensed account in O365)
Set Reply-to: yes

in Office 365:
Set up an exchange connector from "your organization's email server" to Office 365, and specify by IP, and add your Magento 2 servers public IP.

Lastly: Make sure any other email addresses you want the donotreply@yourdomain.com to send as, that THOSE accounts have the donotreply@yourdomain.com address in its send-as field.

Feel free to add this to the Front Page Wiki.

**Comment by srenon** [comment]
@spyrule .. thanks for providing the setting

**Comment by ivan-krechko** [comment]
+ pay attention on Email Sender in all over the Configuration.

**Comment by spyrule** [comment]
@ivan-krechko Do you mean throughout the email configuration options in the configuration panel?
If you are, then they all have to be from the same domain, but as long as you set the permissions on those send-as email addresses to allow the donotreply@yourdomain.com to send-as, then it effectively works as an email relay account.

**Comment by ivan-krechko** [comment]
Yes. )
