### ISSUE TITLE
Issue when compiling site

### ISSUE THREAD

**Issue by 9SL9** [magepal/magento2-gmailsmtpapp#6]
I just followed your instructions to install this app. The installation appears to go ok except I'm getting the following error when running: magenta setup:di:compile

I'm now unable to use my site (white screen on admin login). Any ideas??????? 

Errors during compilation:
	MagePal\GmailSmtpApp\Controller\Adminhtml\Test\Index
		Extra parameters passed to parent construct: $dataHelper. File: /var/www/html/magento/app/code/MagePal/GmailSmtpApp/Controller/Adminhtml/Test/Index.php
	MagePal\GmailSmtpApp\Block\Adminhtml\System\Config\TestButton
		Incorrect dependency in class MagePal\GmailSmtpApp\Block\Adminhtml\System\Config\TestButton in /var/www/html/magento/app/code/MagePal/GmailSmtpApp/Block/Adminhtml/System/Config/TestButton.php
\Magento\Framework\UrlInterface already exists in context object
Total Errors Count: 2
Errors during compilation:
	MagePal\GmailSmtpApp\Controller\Adminhtml\Test\Index
		Extra parameters passed to parent construct: $dataHelper. File: /var/www/html/magento/app/code/MagePal/GmailSmtpApp/Controller/Adminhtml/Test/Index.php
	MagePal\GmailSmtpApp\Block\Adminhtml\System\Config\TestButton
		Incorrect dependency in class MagePal\GmailSmtpApp\Block\Adminhtml\System\Config\TestButton in /var/www/html/magento/app/code/MagePal/GmailSmtpApp/Block/Adminhtml/System/Config/TestButton.php
\Magento\Framework\UrlInterface already exists in context object
Total Errors Count: 2
Errors during compilation:
	MagePal\GmailSmtpApp\Controller\Adminhtml\Test\Index
		Extra parameters passed to parent construct: $dataHelper. File: /var/www/html/magento/app/code/MagePal/GmailSmtpApp/Controller/Adminhtml/Test/Index.php
	MagePal\GmailSmtpApp\Block\Adminhtml\System\Config\TestButton
		Incorrect dependency in class MagePal\GmailSmtpApp\Block\Adminhtml\System\Config\TestButton in /var/www/html/magento/app/code/MagePal/GmailSmtpApp/Block/Adminhtml/System/Config/TestButton.php
\Magento\Framework\UrlInterface already exists in context object
Total Errors Count: 2

**Comment by srenon** [comment]
I'm reviewing this.

To get the site backup and running what happen if you run  `bin/magento  setup:upgrade`

**Comment by 9SL9** [comment]
I just tried your suggestion. The command runs and completes successfully but still no login.

**Comment by srenon** [comment]
Try flush cache `bin/magento cache:flush`

**Comment by 9SL9** [comment]
Tried that, still no luck. See here for an error from my log which I'm getting since my failed install:

http://magento.stackexchange.com/questions/103374/white-admin-login-screen-on-magento-2

**Comment by 9SL9** [comment]
My white screen issue is now fixed..

**Comment by srenon** [comment]
What method fixed it?

**Comment by 9SL9** [comment]
fixing ownership on var

**Comment by srenon** [comment]
ok.... R.S = srenon

**Comment by 9SL9** [comment]
:)

**Comment by 9SL9** [comment]
But do we still have an issue with your app? I'm hesitant to try it again..

**Comment by srenon** [comment]
Yes... I'm trying to figure what the errors and fix them

**Comment by srenon** [comment]
Download the latest and try again

**Comment by 9SL9** [comment]
White admin login after installing..

**Comment by srenon** [comment]
Did you do `bin/magento setup:upgrade`

**Comment by 9SL9** [comment]
yes

**Comment by srenon** [comment]
1. Check your error log
2. Delete your var/di

Which method did you use to install the module (manual or composer)?

**Comment by 9SL9** [comment]
Just tried again from scratch using manual and same outcome. Deleted var/di

here's some output:
The following modules have been enabled:
- MagePal_GmailSmtpApp

To make sure that the enabled modules are properly registered, run 'setup:upgrade'.
Cache cleared successfully.
Generated classes cleared successfully. Please re-run Magento compile command
Generated static view files cleared successfully.

php -f bin/magento setup:upgrade
Cache cleared successfully
File system cleanup:
/var/www/html/magento/var/generation/Composer
/var/www/html/magento/var/generation/Magento
/var/www/html/magento/var/generation/Symfony
The directory '/var/www/html/magento/var/di/' doesn't exist - skipping cleanup
Updating modules:
Schema creation/updates:
...
...
Please re-run Magento compile command
bin/magento setup:di:compile
Compilation was started.
Interception cache generation... 7/7 [============================] 100% 3 mins 371.5 MiBB5 MiB
Generated code and dependency injection configuration successfully.

----

unable to login..

**Comment by 9SL9** [comment]
How do I enable logging/which log do I look in?

**Comment by srenon** [comment]
1. Does it work without compile?

2. Try to isolate the issue by deleting MagePal_GmailSmtpApp (move it to a different location) and re-run setup

3. What is the output of `bin/magento deploy:mode:show`

4. Take a look at your apache log and magento log at var/log (ie `tail -f var/log/*`)

**Comment by 9SL9** [comment]
From my apache.log - the following occurs after installing your app and after trying to login as admin (with blank screen)

[Thu Feb 25 16:23:42.552648 2016] [:error] [pid 1597] [client 60.231.62.82:50292] PHP Fatal error:  Uncaught exception 'Magento\\Framework\\Exception\\LocalizedException' with message 'Can't create directory /var/www/html/magento/var/generation/Magento/Framework/App/ResourceConnection/.' in /var/www/html/magento/vendor/magento/framework/Code/Generator.php:103\nStack trace:\n#0 /var/www/html/magento/vendor/magento/framework/Code/Generator/Autoloader.php(35): Magento\\Framework\\Code\\Generator->generateClass('Magento\\Framewo...')\n#1 [internal function]: Magento\\Framework\\Code\\Generator\\Autoloader->load('Magento\\Framewo...')\n#2 [internal function]: spl_autoload_call('Magento\\Framewo...')\n#3 /var/www/html/magento/vendor/magento/framework/Code/Reader/ClassReader.php(19): ReflectionClass->__construct('Magento\\Framewo...')\n#4 /var/www/html/magento/vendor/magento/framework/ObjectManager/Definition/Runtime.php(44): Magento\\Framework\\Code\\Reader\\ClassReader->getConstructor('Magento\\Framewo...')\n#5 /var/www/html/magento/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(71): Magento\\Framework\\ObjectManager\\ in /var/www/html/magento/vendor/magento/framework/Code/Generator.php on line 103

**Comment by srenon** [comment]
That is a permission issue again /var/www/html/magento/var/

**Comment by 9SL9** [comment]
Ok that is fixed. But now I'm getting the following error when trying to send a test email:

5.7.9 Please log in with your web browser and then try again. Learn more at 5.7.9 https://support.google.com/mail/answer/78754 144sm14500496pfa.83 - smtp

I've followed the instructions on that page but still getting this error. correct password checked etc...

**Comment by srenon** [comment]
Did you follow option #2 https://support.google.com/accounts/answer/6010255

**Comment by 9SL9** [comment]
It appears to be working now...Thanks.
