### ISSUE TITLE
mails are going in spam box

### ISSUE THREAD

**Issue by mediameta** [magepal/magento2-gmailsmtpapp#61]
The mails are sent but are placed in  spam box of receiver. How to fix that. seems that SPF and DKIM are incorrect.

**Comment by collymore** [comment]
SPF and DKIM are not configured or managed from this module. 

Please update your DNS records to add the correct SPF and DKIM records to indicate which IP emails are allowed to originate from. 

You can find guides here
SPF : https://support.google.com/a/answer/178723?hl=en
DKIM : https://support.google.com/a/answer/174124?hl=en

**Comment by srenon** [comment]
@mediameta ... let me know if you still having issues.
