### ISSUE TITLE
Connection time out error and not working with TLS 

### ISSUE THREAD

**Issue by rizvanvadia** [magepal/magento2-gmailsmtpapp#62]
Hi, 

I did set below configuration in my magento backend.  

https://www.screencast.com/t/gK0dFRseW 

I am getting timeout error. 

https://www.screencast.com/t/8a80dnI76 

If I change SSL type to TSL and port 587 https://www.screencast.com/t/4AVVUmi2vl21 test email is working but other magneto emails are still fired by default php email through our local server.  Is there any setting at server to use SMTP settings from magento or there is any bug in extension or Magento which is not taking this smtp settings correctly. 

Regards,
Rizvan

**Comment by srenon** [comment]
Timeout normally means that something is blocking the connection to the server... 
Take a look at https://github.com/magepal/magento2-gmailsmtpapp/issues/58

**Comment by rizvanvadia** [comment]
Time out is only on ssl. 

When I use TSL its sending test email but other emails of magento is still from local server not via SMTP.  Is there any setting at server to use SMTP in magento OR there is any bug in extension or Magento which is not taking this smtp settings correctly.

**Comment by srenon** [comment]
What steps did you take to install in extension?

**Comment by rizvanvadia** [comment]
We did install this extension zip file copied files to app/code and then deployed magento 2

**Comment by srenon** [comment]
What mode is Magento in?
Did you do DI compile/flash cache?
Do you have any other email extension installed (that rewrite `\Magento\Framework\Mail\Transport` https://github.com/magepal/magento2-gmailsmtpapp/blob/master/etc/di.xml)?

**Comment by rizvanvadia** [comment]
What mode is Magento in? 

---Production mode

Did you do DI compile/flash cache?
---No
Do you have any other email extension installed (that rewrite \Magento\Framework\Mail\Transport https://github.com/magepal/magento2-gmailsmtpapp/blob/master/etc/di.xml)?
--No other extension

**Comment by srenon** [comment]
Take a look at http://devdocs.magento.com/guides/v2.1/config-guide/prod/single-machine-deployment.html

**Comment by rizvanvadia** [comment]
I am sorry but what is related to extension is not working its installed correct sending test emails the only issue is its not hooked with magento emails? Can you please suggest what may be issue with this?

**Comment by srenon** [comment]
"magneto emails are still fired by default php email through our local server"... this is what you state correct?

The only way that is possible is if this (https://github.com/magepal/magento2-gmailsmtpapp/blob/master/etc/di.xml) is not merged or this (https://github.com/magepal/magento2-gmailsmtpapp/blob/master/Plugin/Mail/TransportPlugin.php#L28) returning false.

**Comment by srenon** [comment]
@rizvanvadia .... I will close this ticket since you have not replied in over 20 days
