### ISSUE TITLE
Get error in log when sending magento email 

### ISSUE THREAD

**Issue by impunkj** [magepal/magento2-gmailsmtpapp#63]
Test mail is working fine but when using magento email it will not send any email and after check system.log it display 
[2017-06-01 10:25:31] main.ERROR: Syntax error in parameters or arguments
Please if someone help that how to debug this.

Thanks

**Comment by srenon** [comment]
@impunkj ... did you try disabling the module to see if this is a module issue or a system issue?

**Comment by impunkj** [comment]
@srenon Thanks for your reply what should i do i just remove completely this module or just disable this from admin panel.

**Comment by impunkj** [comment]
After Disable From admin panel email is working.

**Comment by srenon** [comment]
Try putting your store in developer mode (see http://devdocs.magento.com/guides/v2.0/config-guide/cli/config-cli-subcommands-mode.html) so you can figure out the exact error msg.

**Comment by srenon** [comment]
@impunkj ... I will be close this ticket since you have not replied in over 20 days.
