### ISSUE TITLE
about some problem after transfer website

### ISSUE THREAD

**Issue by ryoting** [magepal/magento2-gmailsmtpapp#64]
hi,author:
my website have install this module.recently,i transfer my website to another server,the domain name hasn't changed,but this module can't work.send test mail tips:
‘Result
Connection timed out’
my new server's php version is php 7.0.19
if something must to be modified?
thanks very much.

**Comment by srenon** [comment]
Was it working before you move domain?

"Connection timed out" normally have something to do with port blocked or php mail not configure properly.

ssh into your server and run ``php -r "mail('s@gmail.com', 'My Subject', 'test');"``. what is the output?

**Comment by ryoting** [comment]
sh: -t: command not found

**Comment by srenon** [comment]
This module require php mailserver to be working (on localhost or another server)

**Comment by ryoting** [comment]
but my first server is not installed mailserver,however,it work well.that php version is 7.0.12

**Comment by srenon** [comment]
You need to install on your server "sendmail" or equivalent

**Comment by ryoting** [comment]
OK,I has known what's wrong,my service provider blocked port 25.......my god!!!

thank you !
