### ISSUE TITLE
error on composer require magepal/magento2-gmailsmtpapp

### ISSUE THREAD

**Issue by Darrendeng12** [magepal/magento2-gmailsmtpapp#66]
How to fix this?

Root package 'magepal/magento2-gmailsmtpapp' cannot require itself in its composer.json
Did you accidentally name your root package after an external package?

How can i solve this error?
the project directory is /r {Magento root}/vendor/MagePal/GmailSmtpApp

**Comment by Darrendeng12** [comment]
the magento version is Magento Community Edition 2.1.7

**Comment by srenon** [comment]
The folder structure that composer create should be
```{Magento root}/vendor/magepal/magento2-gmailsmtpapp```

**Comment by srenon** [comment]
Are you running composer from magento root folder?

See
https://laracasts.com/discuss/channels/laravel/composer-require-laravelhomestead-doesnt-work
https://github.com/firebase/php-jwt/issues/112
https://github.com/NicklasWallgren/PokemonGoAPI-PHP/issues/95

**Comment by Darrendeng12** [comment]
I have just tried running the composer from magento2-gmailsmtpapp folder
I did those steps and still have the same error

**Comment by Darrendeng12** [comment]
@srenon thank,I think I know how to fix this error
