### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by jpcsguru** [magepal/magento2-gmailsmtpapp#67]
fails to work on magento 2.1.5

**Comment by srenon** [comment]
There are no code changes in 2.1.5, so if you provide more information I would be more than happy to try to help.

> This release updates the copyright date in every file. It does not contain any functional changes or security improvements. Isolating these changes in a single release is intended to simplify future updates and developer workflow.

http://devdocs.magento.com/guides/v2.1/release-notes/ReleaseNotes2.1.5CE.html

**Comment by jpcsguru** [comment]
Hi,
   when installed it does not show

**Comment by jpcsguru** [comment]
tried install in magento and by composer

**Comment by jpcsguru** [comment]
can you send steps to install by composer please, see i missed anything

**Comment by srenon** [comment]
See https://github.com/magepal/magento2-gmailsmtpapp/blob/master/README.md#using-composer-from-magento-root-dir-run

**Comment by jpcsguru** [comment]
thanks
followed that no good

**Comment by srenon** [comment]
"no good" means nothing to me ... so if you provide more information I will be more than happen to help. 

This module has been download over 12k times, so more than likely the module is not the issue.

**Comment by srenon** [comment]
Does ``vendor/magepal/magento2-gmailsmtpapp/`` folder exist and contain all the files in the repo?

**Comment by jpcsguru** [comment]
yes

**Comment by srenon** [comment]
From your Magento root run ``php bin/magento module`` is MagePal_GmailSmtpApp listed as been enabled?

Are you using a Magento admin user with full priveledges?

**Comment by jpcsguru** [comment]
i have got it working 1 file was missing

**Comment by jpcsguru** [comment]
Hi,
   wat setting do i need to run my mailserver?

**Comment by jpcsguru** [comment]
How do we config module

**Comment by jpcsguru** [comment]
Hi,
   wat setting do i need to run my mailserver?

**Comment by jpcsguru** [comment]
Hi,
   wat setting do i need to run my mailserver?
