### ISSUE TITLE
  [InvalidArgumentException]   Graph node 'MagePal_GmailSmtpApp' is linked to itself

### ISSUE THREAD

**Issue by kytan91** [magepal/magento2-gmailsmtpapp#69]
i am facing this issue when try to enable or disable any module including try to disable the magepal this module. Can you please guide me ?

  [InvalidArgumentException]   
Graph node 'MagePal_GmailSmtpApp' is linked to itself

module:enable [-f|--force] [--all] [-c|--clear-static-content] [--magento-init-params="..."] [mo

Thanks!!
![20170712134143](https://user-images.githubusercontent.com/30074078/28103455-6b7fa3b4-6708-11e7-8bb3-b54a39205b48.jpg)

**Comment by kytan91** [comment]
i am not able to disable or enable/uninstall any module this moment

**Comment by srenon** [comment]
@kytan91 .. How did you install the module (by composer or manual)?

Try (from your Magento root) ```rm -fr var/generation/* var/cache/mage-*```

**Comment by kytan91** [comment]
solve alredy thanks!

**Comment by srenon** [comment]
@kytan91 ... what was the issue?

**Comment by erikatbusteco** [comment]
I think it was a wrong require in the composer.json file , a require which referenced the module itself
