### ISSUE TITLE
5.7.8 Username and Password not accepted after save config on magento2 

### ISSUE THREAD

**Issue by knidie** [magepal/magento2-gmailsmtpapp#7]
its working before i save the config ,i try the mail setting test and it works ,after i saved the config on magento2 i try again mail test , i get 5.7.8 Username and Password not accepted,how i can  fix it

**Comment by srenon** [comment]
What version of 2.x are you using?
Are you using multiple store?

**Comment by knidie** [comment]
hi 
  I’m using 2.0.2 version of magento2.
no , i use single-store mode.

**Comment by srenon** [comment]
If you retype the username/password (without saving) does it sill work?

**Comment by knidie** [comment]
yes if i retype password without saving the email test will work

**Comment by srenon** [comment]
Which option is check at https://www.google.com/settings/security/lesssecureapps?

**Comment by knidie** [comment]
for less secure apps was allowed

**Comment by srenon** [comment]
Are you a developer or are you comfortable with making simple code changes so that we can see what the issue is?

**Comment by knidie** [comment]
im not a developer but i can try to do it

**Comment by knidie** [comment]
what i have to do

**Comment by srenon** [comment]
I want you to check to make sure the password is the same after saving

So go to /Controller/Adminhtml/Test/Index.php

Change 

` $result = __('Sent... Please check your email') . ' ' . $to;`

to

 `$result = __('Sent... Please check your email') . ' ' . $to . " u: {$username} p: {$password}";`

The popup will show you the username and password (remember to change back once finish)

**Comment by knidie** [comment]
where i can find this folder ? it is in magento2 root folder?

**Comment by srenon** [comment]
Base on which method you use to install it either in app/code/MagePal/GmailSmtpApp or in vender/magento/magento2-gmailsmtpapp

**Comment by knidie** [comment]
i just did what you said now ill go test it

**Comment by knidie** [comment]
without save config test mail popup username and password right, then i save config try test again it popup "5.7.8 Username and Password not accepted. Learn more at 5.7.8  https://support.google.com/mail/answer/14257 <https://support.google.com/mail/answer/14257> p125sm16820391wmd.16 - smtp"

**Comment by srenon** [comment]
Sorry, undo that change and do this instead

change
`$this->getResponse()->setBody($this->makeClickableLinks($result));`

to 

$this->getResponse()->setBody($this->makeClickableLinks($result) . " u: {$username} p: {$password}");

**Comment by knidie** [comment]
the password show like this "p: ��)����” username is normal
> 在 2016年2月29日，下午5:06，R.S <notifications@github.com> 写道：
> 
> . " u: {$username} p: {$password}"

**Comment by srenon** [comment]
Does your password contain special characters? Do you know your database character set

**Comment by knidie** [comment]
no special characters its normal upcase letter and numbers. i just checked my database character set  it is in latin1.

**Comment by srenon** [comment]
Try enter your password as `abc123` then save and test config. Does it show `abc123`?

**Comment by knidie** [comment]
i input abc123 and save config  then password like this  "p: �vMu$Yt�"

**Comment by srenon** [comment]
Log into your database. Go to `core_config_data` table then search for `system/gmailsmtpapp/password`

or

`SELECT * FROM mage2.core_config_data where path like '%system/gmailsmtpapp/password%'`

Is the password `abc123` or does it seem encrypted?

**Comment by knidie** [comment]
+-----------+---------+----------+------------------------------+-----------------------------------------------------------------------------------+
| config_id | scope   | scope_id | path                         | value                                                                             |
+-----------+---------+----------+------------------------------+-----------------------------------------------------------------------------------+
|        55 | default |        0 | system/gmailsmtpapp/password | 0:2:yj8NM0gv9NLiZQv1jucUkiW65op1mOSK:OLWp9C43EfeNwzvTWmVKkWBx5lRULo6dgRMWMy50eog= |
+-----------+---------+----------+------------------------------+-----------------------------------------------------------------------------------+

**Comment by srenon** [comment]
Try deleting that row and resave (using the same password as above)

**Comment by knidie** [comment]
i can not find how to delete it

**Comment by srenon** [comment]
What program are you use to interact with the db?

**Comment by knidie** [comment]
terminal,I’m connect linux server through terminal.

**Comment by srenon** [comment]
Always backup

`DELETE from core_config_data where config_id = 55 LIMIT 1`

**Comment by knidie** [comment]
+-----------+---------+----------+------------------------------+-----------------------------------------------------------------------------------+
| config_id | scope   | scope_id | path                         | value                                                                             |
+-----------+---------+----------+------------------------------+-----------------------------------------------------------------------------------+
|        84 | default |        0 | system/gmailsmtpapp/password | 0:2:E4bZE6qPyRJ7FvNMactdYpeVWJQ4L7ug:EZl2XyTl0GFZh0QMekHj/cRyNyRlUuplJ9MA5IMFA0w= |
+-----------+---------+----------+------------------------------+-----------------------------------------------------------------------------------+

**Comment by srenon** [comment]
Are you still have an issue connecting to gmail?

The issue is cause by encrypting and decrypting not working correctly similar to these

https://github.com/magento/magento2/issues/2984

https://github.com/magento/magento2/issues/1223

What version of php are you using?

**Comment by knidie** [comment]
i actually using php 7 , is the php7 cause this issue? if i change php to 5.6 it will work normally ?

**Comment by srenon** [comment]
I think so, can you test on v5.6 and let me know. 

On v7 you could also try https://github.com/magento/magento2/commit/32ca5c97304a1bd84cfbee7cec3d57c9307da9a6 or https://github.com/magento/magento2/pull/3054/files

**Comment by knidie** [comment]
sure i’ll let you know. and  thank you for all help.

**Comment by knidie** [comment]
fix the issue on php7 with link you give me, now working fin. 
tested with php 5.6 ,no issue fund.

**Comment by srenon** [comment]
Are you still having issues?

**Comment by knidie** [comment]
how can i configure this app send different email addresses, like ”noreply@gmail.com”send email for account registration ,”support@gmail.com”for support.

**Comment by srenon** [comment]
This work exactly the same as default magento, therefore it will use whatever is set in magento

For example in contact

![image](https://cloud.githubusercontent.com/assets/1415141/13428598/833617ca-df89-11e5-9d90-1716fe11a8bd.png)

Will using the information in "Custom Email 2"

![image](https://cloud.githubusercontent.com/assets/1415141/13428565/45337b2a-df89-11e5-8600-01eef8c35cf0.png)

**Comment by knidie** [comment]
maybe i didn’t  explain well, i have multi gmail addresses, i want use my owner@gmail.com for general contact sender mail, and support@gmail.com as customs support sender mail ,is that possible.

**Comment by srenon** [comment]
No, that not possible because you would need to setup two set of user name and password.

You could setup a 'no-reply@company.com' then have the reply-to set to the different email address (as shown in the previous email). The original message won't be send thru that email but all other correspondent

**Comment by knidie** [comment]
I see, i have no more questions.

**Comment by liquidia** [comment]
i still have this issue using latest version 2.1 with php7
