### ISSUE TITLE
Can not use Component Manager after install magento2-gmailsmtpapp

### ISSUE THREAD

**Issue by mberkman** [magepal/magento2-gmailsmtpapp#70]
When i try to go to Component Manager section, it keep charging. In console i see that it is throwing the following internal server error:

RuntimeException

File:
/var/www/Namespace/magento2/setup/src/Magento/Setup/Model/PackagesData.php:88
Message:
Couldn't get available versions for package magepal/magento2-gmailsmtpapp

**Comment by srenon** [comment]
@mberkman ... Are you trying to reinstall Magento?

**Comment by mberkman** [comment]
No, i trying to install a new module using the Web Setup Wizard

**Comment by srenon** [comment]
What method did you use to install magento2-gmailsmtpapp?

Take a look at https://github.com/splendidinternet/Magento2_German_LocalePack_de_DE/issues/42

**Comment by mberkman** [comment]
I installed it by composer, as documentation says.

**Comment by srenon** [comment]
I'm going to close this ticket since this is a core issue and also affect other third-party extensions.
