### ISSUE TITLE
From field should pull in Sender Name value.

### ISSUE THREAD

**Issue by sergeifilippov** [magepal/magento2-gmailsmtpapp#72]
Hi,

The **From** header field is currently including only the sender email. This means that on the recipients client will only see the first part of the email address in their **From** field.

eg. We have the following setting in M2

- **trans_email/ident_general/name**: John Smith
- **trans_email/ident_general/email**: info@example.com

#### Current

Currently, the from field will say:

```
From: info@example.com
```

![email](https://user-images.githubusercontent.com/123676/28192821-c0bc5bee-688c-11e7-8463-20a1249911a4.jpg)

#### What it should be

```
From: John Smith <info@example.com>
```

If no value is defined in **trans_email/ident_general/name**, it should be:

```
From: info@example.com
```

**Comment by srenon** [comment]
@sergeifilippov ... I not sure if I understand your issue. This is what an order confirmation email should look like in gmail

![image](https://user-images.githubusercontent.com/1415141/28193122-7ab64e54-6808-11e7-8e9f-44ed6eb20cbf.png)

**Comment by sergeifilippov** [comment]
thanks @srenon for the quick reply. 👍🏻

It does if you do a test using the functionality in the module configuration, but if you do it with an actual order it looks like this even if `trans_email/ident_general/name` is defined.

![email](https://user-images.githubusercontent.com/123676/28193330-de14587e-688f-11e7-99c8-24f581da921e.jpg)

We're on Magento `2.1.5` and `magepal/magento2-gmailsmtpapp` at `1.4.5`

**Comment by srenon** [comment]
I'm not able to replicate your issue, can you test on a fresh install of Magento or preform a test with the module disabled

**Comment by sergeifilippov** [comment]
It was actually a misconfiguration on my end. Sorry guys!

**Comment by ctadlock** [comment]
@srenon What was the fix? I am having this exact issue.

![image](https://user-images.githubusercontent.com/1539397/47236199-3a336c00-d390-11e8-909a-37beffe1d637.png)


![image](https://user-images.githubusercontent.com/1539397/47236179-2daf1380-d390-11e8-89ed-3b5a750c9999.png)

**Comment by ctadlock** [comment]
I think this is a Magento issue: https://github.com/magento/magento2/pull/18472
