### ISSUE TITLE
Error on GMail Test Email

### ISSUE THREAD

**Issue by rdueck** [magepal/magento2-gmailsmtpapp#74]
I'm quite sure I got all my settings right, but when I try sending a test email. I get the following popup message... And then I don't get any email coming through. I'm using Google Account with TLS. and the email address it's sending from is using GSuite. I've also ensured IMAP is enabled on Google.

5.7.14 <https://accounts.google.com/signin/continue?sarp=1&scc=1&plt=AKgnsbuV 5.7.14 6W8FbKNk8PH9hN_t-ZL7xhPIQIjg77ldfw4BhPbCzQ-1EEcJAK6F3JuN1T0zM-_69uJBl- 5.7.14 rT0hQVpuzSOojLZAN4iPt8Bcn0MyBhguR-Ldw_Ciyym_vZK1VJ_i9b4VqbQDzNSLgIR4Zg 5.7.14 U20UvNiWI6a6BpGcgVdxKceU0iHWcDB1MT711D9FIdnKMUAu3KXeuowJEatWG9v2eS_cEN 5.7.14 M6oEIrmT3CrgoYgpcs7K-RZzFl-1Y> Please log in via your web browser and 5.7.14 then try again. 5.7.14 Learn more at 5.7.14 https://support.google.com/mail/answer/78754 t76sm5326521oit.5 - gsmtp

**Comment by ottybrad** [comment]
Getting the same issue

**Comment by srenon** [comment]
@rdueck @ottybrad ... This is not really an error, it is a security feature in Gmail. Please take a look at https://support.google.com/accounts/answer/6010255
