### ISSUE TITLE
Contact Us Error

### ISSUE THREAD

**Issue by Quualudes** [magepal/magento2-gmailsmtpapp#76]
Hi,
I installed this module and it ran great with office365, or so I thought.  Transaction emails, order confirmations, shipping, and invoices all work beautifully.  However the CONTACT US form is not working.  It throws an error "We can't process your request right now. Sorry, that's all we know."

If I disable the module, email works non-encrypted and sends over my default php mail settings.  If I re-enable the module all transaction emails send tls encrypted over outlook smtp, but contact us throws the error again.  

Ideas for the cause of this? I ran an extention conflict module and see no conflicts. 
Thanks!

**Comment by srenon** [comment]
@Quualudes ... Can you check your error logs to see what error you are getting?

**Comment by Quualudes** [comment]
There is no error being generated in any of the logs.

**Comment by Quualudes** [comment]
Issue is resolved.

was this... https://github.com/magento/magento2/issues/6153

Had to disdisable extention, run setup upgrade, compile, deploy, change
email template for contact form, clear caches, static-deploy, enable
template, update, compile, static-deploy.

Was not unique to your extention happened with all smtp modules (i also
tried mageplaza https://github.com/mageplaza/magento-2-smtp), same thing
happened.  Very odd.  Tried a lot of stuff before the template thing
worked.  Nice extention thanks.
