### ISSUE TITLE
"From" email address is always the username configured in admin

### ISSUE THREAD

**Issue by nikolakisae** [magepal/magento2-gmailsmtpapp#8]
Using the Sales Representative Sender Email but the username configured in admin is shown as sender.

**Comment by srenon** [comment]
not sure if I understand your issue. Normally you would want your from/gmail email address be something like web@[store.com] then the reply-to from the various transactional email would be sales@[store.com], cs@[store.com]

**Comment by nikolakisae** [comment]
Exactly...but the gmail address is always shown as the "from email" when i receive it even if i configured to use the  sales@[store.com]. The "from name" is fine but the from email is always the gmail.

**Comment by nikolakisae** [comment]
The details of the email i receive are..
from:	Custom 1 <xxx@gmail.com>
reply-to:   web@[store.com] 

is that correct?

**Comment by srenon** [comment]
Is the reply-to address the same as what entered into "Custom 1"?

**Comment by nikolakisae** [comment]
there is no reply-to address in the email details

**Comment by srenon** [comment]
I will add a fix for this shortly

**Comment by nikolakisae** [comment]
Great!thanks

**Comment by msliman** [comment]
@srenon @nikolakisae Is that problem fixed, because i still have this problem ?
