### ISSUE TITLE
Unable to send mail in Magento 2.2

### ISSUE THREAD

**Issue by magentoprince** [magepal/magento2-gmailsmtpapp#83]
This error message is shown at the time of send mail. And in **debug.log** of Magento 2.2 show this error

> report.CRITICAL: Unable to send mail.  {"exception":"[object] (Magento\\Framework\\Exception\\MailException(code: 0): Unable to send mail.  at /var/www/html/mage22ee/app/code/Magento/Email/Model/Transport.php:112, Zend_Mail_Transport_Exception(code: 0): Unable to send mail.  at /var/www/html/mage22ee/vendor/magento/zendframework1/library/Zend/Mail/Transport/Sendmail.php:111)"} []

**Comment by srenon** [comment]
@magentoprince ... We are working on it ... see https://github.com/magepal/magento2-gmailsmtpapp/issues/82

**Comment by srenon** [comment]
Done ... Please test and let me know if you have any issue

https://github.com/magepal/magento2-gmailsmtpapp/releases/tag/1.5.0

**Comment by gvigner** [comment]
Google servers are banned in China, it's not possible to use gmail. Any alternative ?
