### ISSUE TITLE
Stores -> Configuration -> System is blank

### ISSUE THREAD

**Issue by peterphan2004** [magepal/magento2-gmailsmtpapp#86]
Hi 
  
After installation, the system page is blank.  Currently on Magento2.2.0 with php 7.1.9.
Below are the errors in system.log file.  I verified that hte version file does exist.  A bit lost please help.
 
[2017-11-07 21:53:28] main.CRITICAL: Class MagePal\GmailSmtpApp\Block\Adminhtml\System\Config\Version does not exist [] []
[2017-11-07 21:53:28] main.CRITICAL: Invalid block type: MagePal\GmailSmtpApp\Block\Adminhtml\System\Config\Version [] []

**Comment by srenon** [comment]
Did you installed using composer or manually?

**Comment by peterphan2004** [comment]
I installed manually (downloaded https://github.com/magepal/magento2-gmailsmtpapp/releases) v 1.5.1 and followed the installation instruction.  The module installed with no errors.

**Comment by peterphan2004** [comment]
I tried the composer installation and here's the message i got:   
Using version ^1.5 for magepal/magento2-gmailsmtpapp
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package magento/product-community-edition could not be found in any version, there may be a typo in the package name.
  Problem 2
    - magepal/magento2-gmailsmtpapp 1.5.1 requires magento/module-backend 100.0.*|100.1.*|100.2.* -> no matching package found.
    - magepal/magento2-gmailsmtpapp 1.5.0 requires magento/module-backend 100.0.*|100.1.*|100.2.* -> no matching package found.
    - Installation request for magepal/magento2-gmailsmtpapp ^1.5 -> satisfiable by magepal/magento2-gmailsmtpapp[1.5.0, 1.5.1].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.

**Comment by srenon** [comment]
This is the second time someone reported this issue and I have no idea what causes it, but since there are over 40k download I would think it is an environment issue. Are you using any case-sensitive OS or vargant/vm?

Can you try installed using composer (remember to delete the MagePal folder in app/code)?

**Comment by srenon** [comment]
How did you install Magento, (1) from github using git (2) using composer or (3) download zip from Magento?

**Comment by peterphan2004** [comment]
I've tried the composer installation and got the below message:

Using version ^1.5 for magepal/magento2-gmailsmtpapp
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package magento/product-community-edition could not be found in any version, there may be a typo in the package name.
  Problem 2
    - magepal/magento2-gmailsmtpapp 1.5.1 requires magento/module-backend 100.0.*|100.1.*|100.2.* -> no matching package found.
    - magepal/magento2-gmailsmtpapp 1.5.0 requires magento/module-backend 100.0.*|100.1.*|100.2.* -> no matching package found.
    - Installation request for magepal/magento2-gmailsmtpapp ^1.5 -> satisfiable by magepal/magento2-gmailsmtpapp[1.5.0, 1.5.1].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.

**Comment by peterphan2004** [comment]
Magneto was installed via download

**Comment by srenon** [comment]
Which of these paths contain you Magento classes {magento2}/vendor/magento or {magento2}/app/code/Magento?

Your first issue is 

> The requested package magento/product-community-edition could not be found in any version, there may be a typo in the package name

Take a look at https://github.com/magento/magento2/issues/6453

Your issue doesn't seem to be specific to this module, so if you want you can open a paid ticket to support@magepal.com and we will fix all your issues for you.

**Comment by peterphan2004** [comment]
Thank you for the great support !  I was able to install the module via composer and not able to get it working with the download link.

**Comment by spraxis** [comment]
I got the same error and the problem was that the folder was "Magepal" instead of "MagePal".
