### ISSUE TITLE
Upgrade to Magento 2.2.1 requires plugin to be removed and causes reinstallation issues.

### ISSUE THREAD

**Issue by lundzern** [magepal/magento2-gmailsmtpapp#87]
Hi, in order to be able to update Magento to the latest 2.2.1 release I had to do some tweaks as suggested in [this](https://magento.stackexchange.com/a/197371/48717) answer.

After this, the installation process went through, but the MagePal SMTP plugin stopped working, I have now been trying to uninstall and reinstall using composer.

But when I try to run the `php -f bin/magento module:enable --clear-static-content MagePal_GmailSmtpApp` command to reinstall the plugin I get the following error:

> Autoload error: Module 'MagePal_GmailSmtpApp' from '/opt/bitnami/apps/magento/htdocs/app/code/MagePal/GmailSmtpApp' has been already defined in '/opt/bitnami/apps/magento/htdocs/vendor/magepal/magento2-gmailsmtpapp'

And I get stuck here not knowing what to do in order to sort this out, it seems to me that I will have to remove some remains of the previous plugin before trying to reinstall but I am not sure how to go about this.

**Comment by srenon** [comment]
What version of GmailSmtpApp are you running (see vendor/magepal/magento2-gmailsmtpapp/composer.json) in your environment?

See https://github.com/magepal/magento2-gmailsmtpapp/blob/master/composer.json#L18

**Comment by lundzern** [comment]
Hi @srenon and thanks for your reply (and sorry for my delayed one!)

I found the file you mention in the htdocs/app/code/MagePal/GmailSmtpApp/ folder (not under vendor/ like you said).

Not sure if that has any relevance?

Also, the version number in that file is 1.4.5

**Comment by srenon** [comment]
@lundzern .... You seem to have 2 issues that not a bug in the extension.

1. The module was installed twice (manually and using composer)
2. You are running an old version that may not support M2.2.1.

Since this is not a bug in the module you are more than welcome to open a paid ticket with support@magepal.com and I will have someone set up the module correctly
