### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by NeroNoel** [magepal/magento2-gmailsmtpapp#88]
I've followed all instructions to install.  I can see the configuration options in store configuration settings, so it appears I have been successful.  However when I try to send test e-mail I get this notification.

"**Result

Network is unreachable**"

I have verified the gmail login details are correct.  still no luck.  Any help appreciated.

**Comment by srenon** [comment]
@NeroNoel ..... "Network is unreachable" mean something is blocked
