### ISSUE TITLE
order confirmation email is not sent for guest's order only Magento 2.1

### ISSUE THREAD

**Issue by aramega** [magepal/magento2-gmailsmtpapp#89]
Hi Magepal Team,

In the backend shows (The order confirmation email is not sent), if i clicked on send email it sends the message.

and if the customer logged in its working fine.

Configuration

Sales -> Sales Emails -> General Settings -> Asynchronous sending is Disable

**Comment by srenon** [comment]
@aramega ... I think you have the wrong extension provided

**Comment by aramega** [comment]
@srenon Sorry about that i edited the name, But when we use the magepal team everything working well except the guests email order confirmation.
