### ISSUE TITLE
Need help.can't send mail.

### ISSUE THREAD

**Issue by shuaiZend** [magepal/magento2-gmailsmtpapp#9]
test send is okay.
but other email can't send.
have any log file?where?

**Comment by troncar** [comment]
I have the same problem

**Comment by srenon** [comment]
@shuaiZend  @troncar ... What version of magento and php are you running?

**Comment by troncar** [comment]
Magento 2.0.2

**Comment by srenon** [comment]
What PHP version?

**Comment by shuaiZend** [comment]
@srenon PHP7 and Magento2.0.2

**Comment by srenon** [comment]
@shuaiZend 

This is a bug in magento when using php7 the encrypting and decrypting of system config not working correctly 

See 

https://github.com/magento/magento2/issues/2984

https://github.com/magento/magento2/issues/1223

To fix the issue see

https://github.com/magento/magento2/commit/32ca5c97304a1bd84cfbee7cec3d57c9307da9a6 or https://github.com/magento/magento2/pull/3054/files

**Comment by shuaiZend** [comment]
i used https://github.com/magento/magento2/commit/32ca5c97304a1bd84cfbee7cec3d57c9307da9a6
but Still can't send mail

**Comment by shuaiZend** [comment]
@srenon thank you.
i fixed this.
used https://github.com/magento/magento2/commit/32ca5c97304a1bd84cfbee7cec3d57c9307da9a6

**Comment by shuaiZend** [comment]
@srenon i used your last version...notice `5.7.8 Username and Password not accepted`
But I still use the previous version's user name and password。
Previous versions can be email.

```
[2016-03-20 18:45:38] main.CRITICAL: Exception message: 5.7.8 Username and Password not accepted. Learn more at^M
 5.7.8  https://support.google.com/mail/answer/14257 yy7sm10584180obb.26 - gsmtp^M

Trace: #0 /home/wwwroot/mysite/vendor/magento/module-newsletter/Controller/Subscriber/NewAction.php(124): Magento\Newsletter\Model\Subscriber->subscribe('shuai.zend@hotm...')
#1 /home/wwwroot/mysite/var/generation/Magento/Newsletter/Controller/Subscriber/NewAction/Interceptor.php(24): Magento\Newsletter\Controller\Subscriber\NewAction->execute()
#2 /home/wwwroot/mysite/vendor/magento/framework/App/Action/Action.php(102): Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor->execute()
#3 [internal function]: Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#4 /home/wwwroot/mysite/vendor/magento/framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#5 /home/wwwroot/mysite/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Newsletter\Controller\Subscriber\NewAction\Interceptor->___callParent('dispatch', Array)

```

**Comment by shuaiZend** [comment]
@srenon I try to compare the two databases Email password field in **core_config_data**.
I found a version of the password is encrypted, the latest version is not encrypted.

**Comment by srenon** [comment]
Try re-saving ... and check the password again.

I just reenter my password an php 5.x and it is encrypted.

So this must be a php7 or the changes you make issue

**Comment by shuaiZend** [comment]
I try re-saving password again.
last version is 1.1, previous version is 1.0.
version 1.1 in databases is not encrypted email password.

**Comment by srenon** [comment]
Undo the changes you made for php7 and try saving again

**Comment by shuaiZend** [comment]
I rollback data.php in php7.
and run cil cache:flush
and resaving password again.
still not encrypted.

**Comment by srenon** [comment]
Try doing `bin/magento setup:upgrade` instead. I just test on the dev branch without any issue

**Comment by shuaiZend** [comment]
![image](https://cloud.githubusercontent.com/assets/1478692/13908600/e9b97a2a-ef40-11e5-88d2-207227378ab0.png)


![image](https://cloud.githubusercontent.com/assets/1478692/13908596/ce55c0fe-ef40-11e5-9ec0-ede6195066bd.png)
still not encrypted.

**Comment by srenon** [comment]
A quick way to test to see if this is issue only affect this module is to enable another module that encrypt password (uses `<backend_model>Magento\Config\Model\Config\Backend\Encrypted</backend_model>`) eg payment module

**Comment by troncar** [comment]
@shuaiZend PHP: 5.6.15

**Comment by srenon** [comment]
@troncar ... they should not be any issue with php 5.x. Follow these steps to debug https://github.com/magepal/magento2-gmailsmtpapp/issues/9
