### ISSUE TITLE
magento 2 coupon code with % in code does not work

### ISSUE THREAD

**Issue by magexpert** [magepal/magento2-gmailsmtpapp#92]
Using magento 2.1.5. If we add a coupon code like code10% it does not work. If we use code without % then it works. Anybody had the same issue and how can it be solved.

**Comment by srenon** [comment]
I just tested on M2.2.2 and was not able to replicate the issue. Base on how this module works it next to impossible to cause an issue with coupon. 

![image](https://user-images.githubusercontent.com/1415141/34327457-48d5e91a-e893-11e7-8436-07bc088e673b.png)
