### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by aminisana** [magepal/magento2-gmailsmtpapp#93]
Hello,
I am using magento 2.1
I have the module in myshop/vendor
But it does not appear in the list of modules in the backoffice (configuration / system /advanced)
I added it in myshop/app/code/MagePal/GmailSmtpApp
and when I run this command 
php -f bin/magento module:enable --clear-static-content MagePal_GmailSmtpApp
I have this error
Autoload error: Module 'MagePal_GmailSmtpApp' from '/var/www/html/myshop/app/code/MagePal/GmailSmtpApp' has been already defined in '/var/www/html/myshop/vendor/magepal/magento2-gmailsmtpapp'
Thanks in advance

**Comment by srenon** [comment]
Someone already manually installed the module in `/var/www/html/myshop/app/code/MagePal/GmailSmtpApp`

So you will need to delete it (`rm -fr /var/www/html/myshop/app/code/MagePal/GmailSmtpApp`) then continue to install it using composer.
