### ISSUE TITLE
connection timeout issue from 24 Jan 2018

### ISSUE THREAD

**Issue by fisherman818** [magepal/magento2-gmailsmtpapp#96]
Hi all,

I am using Magento 2.1.0, Google SMTP, and this great application together. All the way (for the past one and half years) it has been working fine, till about 18 hours ago - no more email can be sent, while all the configurations remain no change. Does anyone have the similar experience and can share the solutions? Thanks!

**Comment by srenon** [comment]
@fisherman818 .... 

1. What module version are you using?
2. What SMTP server are you using (google, amazon ..etc)?
3. Did you installed any new extension recently?
4. Did your hosting company made any server configuration changes

Connection timeout normally means something is blocked

**Comment by fisherman818** [comment]
@srenon thank you for the help! My issues were resolved. point 4 mentioned by @srenon was the reason. My hosting company wrongly blocked the SMTP ports from their level. Totally wasted 3 hours troubleshooting.. anyone who encounters this similar issue in the future, please do make sure check with them as well. I did that only because I didn't know what else to do..
